// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"

	affinity "github.com/affinity-health/affinity-go"
	core "github.com/affinity-health/affinity-go/core"
	internal "github.com/affinity-health/affinity-go/internal"
	option "github.com/affinity-health/affinity-go/option"
	invitations "github.com/affinity-health/affinity-go/team/invitations"
	members "github.com/affinity-health/affinity-go/team/members"
	client "github.com/affinity-health/affinity-go/team/prescribers/client"
)

type Client struct {
	WithRawResponse *RawClient
	Invitations     *invitations.Client
	Members         *members.Client
	Prescribers     *client.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Invitations:     invitations.NewClient(options),
		Members:         members.NewClient(options),
		Prescribers:     client.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Requires team:write and Idempotency-Key. Registers a practice member without an invitation. Test requires synthetic .test emails and Affinity Test NPIs. Live requires approved integration and practice access. Identity attestation records the integration's assertion; it does not verify login email or clinical credentials. Existing memberships and verified provider records are preserved. Use the returned user ID for orders and signing.
func (c *Client) Register(
	ctx context.Context,
	request *affinity.RegisterUserRequest,
	opts ...option.RequestOption,
) (*affinity.RegisterUserResponse, error) {
	response, err := c.WithRawResponse.Register(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires team:read. Returns counts of members, invitations, and prescribers. Use the paginated members, prescribers, and invitations collections for individual records. Team access and clinician credentials are shared between Test and Live.
func (c *Client) Get(
	ctx context.Context,
	request *affinity.GetTeamRequest,
	opts ...option.RequestOption,
) (*affinity.GetPracticeTeamResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
