// Code generated by Fern. DO NOT EDIT.

package orders

import (
	context "context"

	affinity "github.com/affinity-health/affinity-go"
	core "github.com/affinity-health/affinity-go/core"
	internal "github.com/affinity-health/affinity-go/internal"
	option "github.com/affinity-health/affinity-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) ListOrders(
	ctx context.Context,
	request *affinity.ListOrdersRequest,
	opts ...option.RequestOption,
) (*affinity.ListOrdersResponse, error) {
	response, err := c.WithRawResponse.ListOrders(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates one unsigned order with 1–20 prescriptions for one patient in one practice. Supply patientId or patient; inline patient creation requires patients:write. Prescriber is optional: select by npi, provider id, or integration-scoped externalId, or leave the draft unassigned until signing. First-use prescriber registration requires team:write. Legacy userId is supported but cannot be combined with prescriber. Idempotency-Key is required.
func (c *Client) CreateOrder(
	ctx context.Context,
	request *affinity.CreateOrderRequest,
	opts ...option.RequestOption,
) (*affinity.CreateOrderResponse, error) {
	response, err := c.WithRawResponse.CreateOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetOrder(
	ctx context.Context,
	request *affinity.GetOrderRequest,
	opts ...option.RequestOption,
) (*affinity.GetOrderResponse, error) {
	response, err := c.WithRawResponse.GetOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requests cancellation. HTTP 200 means the request was handled; check cancellation.status for confirmed, pending, partial, or failed. Only confirmed means the entire order is cancelled. Shipment possession makes a fulfillment cancellation too late.
func (c *Client) CancelOrder(
	ctx context.Context,
	request *affinity.CancelOrderRequest,
	opts ...option.RequestOption,
) (*affinity.CancelOrderResponse, error) {
	response, err := c.WithRawResponse.CancelOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Acknowledge, retry, contact, or resolve an order exception in the credential's Test/Live mode. assign_to_me requires a signed-in dashboard user; API keys receive 400 and may use acknowledge instead. Actor headers do not create a dashboard assignee.
func (c *Client) ActOnOrderException(
	ctx context.Context,
	request *affinity.ActOnOrderExceptionRequest,
	opts ...option.RequestOption,
) (*affinity.ActOnOrderExceptionResponse, error) {
	response, err := c.WithRawResponse.ActOnOrderException(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListOrderEvents(
	ctx context.Context,
	request *affinity.ListOrderEventsRequest,
	opts ...option.RequestOption,
) (*affinity.ListOrderEventsResponse, error) {
	response, err := c.WithRawResponse.ListOrderEvents(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires orders:write. Available only in Test mode.
func (c *Client) GetOrderTestSimulation(
	ctx context.Context,
	request *affinity.GetOrderTestSimulationRequest,
	opts ...option.RequestOption,
) (*affinity.GetOrderTestSimulationResponse, error) {
	response, err := c.WithRawResponse.GetOrderTestSimulation(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires orders:write and Idempotency-Key. Configure before submission or queue a valid pharmacy event in manual mode. Events use normal order history and Test webhooks. Live requests are rejected.
func (c *Client) UpdateOrderTestSimulation(
	ctx context.Context,
	request *affinity.UpdateOrderTestSimulationRequest,
	opts ...option.RequestOption,
) (*affinity.UpdateOrderTestSimulationResponse, error) {
	response, err := c.WithRawResponse.UpdateOrderTestSimulation(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires orders:write and catalog:read. Supply exactly one of patientId, patientExternalId, or inline patient details. External-ID lookup additionally requires patients:read; inline details require patients:write. Resolves defaults and explicit edits for 1–20 prescriptions. Reuses stored patient details when identifiers match; otherwise previews inline details without creating a patient. Complete previews contain an orders.create input. Does not create records, reserve prices, sign, charge or transmit. No idempotency key is required. Creation and signing recheck current requirements.
func (c *Client) PreviewOrder(
	ctx context.Context,
	request *affinity.PreviewOrderRequest,
	opts ...option.RequestOption,
) (*affinity.PreviewOrderResponse, error) {
	response, err := c.WithRawResponse.PreviewOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires orders:sign, Idempotency-Key, signatureAttestation, and expectedRevision from the reviewed order. Existing integrations may send expectedVersions instead; supply exactly one. A stale revision returns 409 and requires renewed clinician review. Select prescriber by npi, provider id, or integration-scoped externalId, or inherit the draft's prescriber. First-use registration requires team:write. Actor headers are optional audit metadata with prescriber; legacy userId requires matching clinician actor headers. Signing does not submit to a pharmacy.
func (c *Client) SignOrder(
	ctx context.Context,
	request *affinity.SignOrderRequest,
	opts ...option.RequestOption,
) (*affinity.SignOrderResponse, error) {
	response, err := c.WithRawResponse.SignOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires orders:sign, Idempotency-Key, signatureAttestation, and expectedRevision from the reviewed order. Existing integrations may send expectedVersions instead; supply exactly one. A stale revision returns 409 and requires renewed clinician review. Select prescriber by npi, provider id, or externalId, or inherit the draft's prescriber. First-use registration requires team:write. Actor headers are optional with prescriber; legacy userId requires matching clinician actor headers. Signs the complete order, then attempts each submission. Signing remains committed if submission fails. Replay the same key after an uncertain response; retry reported submission failures through Submit order with a new key. Submitted means queued, not pharmacy acceptance.
func (c *Client) SignAndSubmitOrder(
	ctx context.Context,
	request *affinity.SignAndSubmitOrderRequest,
	opts ...option.RequestOption,
) (*affinity.SignAndSubmitOrderResponse, error) {
	response, err := c.WithRawResponse.SignAndSubmitOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires orders:sign and Idempotency-Key. Queues signed prescriptions after rechecking authorization, signature integrity, billing, and fulfillment eligibility. Track pharmacy acceptance through order reads and webhooks. After a partial failure, retry submission with a new idempotency key; already queued prescriptions are not duplicated.
func (c *Client) SubmitOrder(
	ctx context.Context,
	request *affinity.SubmitOrderRequest,
	opts ...option.RequestOption,
) (*affinity.SubmitOrderResponse, error) {
	response, err := c.WithRawResponse.SubmitOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires orders:sign and Idempotency-Key. Select a prescriber or inherit the draft's prescriber. Legacy userId requires matching clinician actor headers. Supply expectedRevision from the reviewed order, or expectedVersions for existing integrations. Permanently rejects the complete unsigned order after checking its revision.
func (c *Client) RejectOrder(
	ctx context.Context,
	request *affinity.RejectOrderRequest,
	opts ...option.RequestOption,
) (*affinity.RejectOrderResponse, error) {
	response, err := c.WithRawResponse.RejectOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires orders:write, Idempotency-Key and expectedRevision from the order being edited. Existing integrations may send expectedVersions instead; supply exactly one. Adds a complete prescription to an unsigned Order and returns all new versions. Omitted actor context defaults to the authenticated service account as a system actor. Patient and prescriber attribution stay fixed. Signed orders cannot be amended through this endpoint. Signing and submission require orders:sign through their separate endpoints.
func (c *Client) AddOrderPrescription(
	ctx context.Context,
	request *affinity.AddOrderPrescriptionRequest,
	opts ...option.RequestOption,
) (*affinity.AddOrderPrescriptionResponse, error) {
	response, err := c.WithRawResponse.AddOrderPrescription(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires orders:write, Idempotency-Key and expectedRevision from the order being edited. Existing integrations may send expectedVersions instead; supply exactly one. Replaces one prescription with complete medication instructions and returns all new versions. Omitted actor context defaults to the authenticated service account as a system actor. Patient and prescriber attribution stay fixed. Signed orders cannot be amended through this endpoint. Signing and submission require orders:sign through their separate endpoints.
func (c *Client) UpdateOrderPrescription(
	ctx context.Context,
	request *affinity.UpdateOrderPrescriptionRequest,
	opts ...option.RequestOption,
) (*affinity.UpdateOrderPrescriptionResponse, error) {
	response, err := c.WithRawResponse.UpdateOrderPrescription(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates 1–20 orders for distinct patients in one practice, each with 1–20 prescriptions. Each accepts patientId or inline patient details. Orders and newly created patients commit atomically; any failure saves none. Requires orders:write and Idempotency-Key; inline patients also require patients:write. Omitted actor context defaults to the authenticated service account as a system actor. Sign and submit each resulting order separately using orders:sign.
func (c *Client) CreateOrderBatch(
	ctx context.Context,
	request *affinity.CreateOrderBatchRequest,
	opts ...option.RequestOption,
) (*affinity.CreateOrderBatchResponse, error) {
	response, err := c.WithRawResponse.CreateOrderBatch(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
