// Code generated by Fern. DO NOT EDIT.

package team_members_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	affinity "github.com/affinity-health/affinity-go"
	client "github.com/affinity-health/affinity-go/client"
	option "github.com/affinity-health/affinity-go/option"
	team "github.com/affinity-health/affinity-go/team"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestTeamMembersListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &team.ListMembersRequest{
		PracticeID: "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		StartingAfter: affinity.String(
			"mbr_01j2y8m6jcc9tt24af5pw9x1bc",
		),
		EndingBefore: affinity.String(
			"mbr_01j2y8m6jcc9tt24af5pw9x1bc",
		),
	}
	_, invocationErr := client.Team.Members.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTeamMembersListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTeamMembersListWithWireMock", "GET", "/v1/practices/prac_01j2y8m6jcc9tt24af5pw9x1bc/team/members", map[string]interface{}{"startingAfter": "mbr_01j2y8m6jcc9tt24af5pw9x1bc", "endingBefore": "mbr_01j2y8m6jcc9tt24af5pw9x1bc"}, 1)
}

func TestTeamMembersGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &team.GetMembersRequest{
		PracticeID: "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		MemberID:   "mbr_01j2y8m6jcc9tt24af5pw9x1bc",
	}
	_, invocationErr := client.Team.Members.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTeamMembersGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTeamMembersGetWithWireMock", "GET", "/v1/practices/prac_01j2y8m6jcc9tt24af5pw9x1bc/team/members/mbr_01j2y8m6jcc9tt24af5pw9x1bc", nil, 1)
}

func TestTeamMembersUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &team.UpdatePracticeTeamMemberRequest{
		PracticeID: "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		MemberID:   "mbr_01j2y8m6jcc9tt24af5pw9x1bc",
	}
	_, invocationErr := client.Team.Members.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTeamMembersUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTeamMembersUpdateWithWireMock", "PATCH", "/v1/practices/prac_01j2y8m6jcc9tt24af5pw9x1bc/team/members/mbr_01j2y8m6jcc9tt24af5pw9x1bc", nil, 1)
}
