// Code generated by Fern. DO NOT EDIT.

package affinity

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/affinity-health/affinity-go/internal"
	big "math/big"
)

var (
	createPlatformPracticeAPIKeyRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	createPlatformPracticeAPIKeyRequestFieldPracticeID     = big.NewInt(1 << 1)
	createPlatformPracticeAPIKeyRequestFieldAllowedIps     = big.NewInt(1 << 2)
	createPlatformPracticeAPIKeyRequestFieldExpiresAt      = big.NewInt(1 << 3)
	createPlatformPracticeAPIKeyRequestFieldName           = big.NewInt(1 << 4)
	createPlatformPracticeAPIKeyRequestFieldScopes         = big.NewInt(1 << 5)
)

type CreatePlatformPracticeAPIKeyRequest struct {
	IdempotencyKey string                                          `json:"-" url:"-"`
	PracticeID     string                                          `json:"-" url:"-"`
	AllowedIps     []string                                        `json:"allowedIps,omitempty" url:"-"`
	ExpiresAt      *string                                         `json:"expiresAt,omitempty" url:"-"`
	Name           string                                          `json:"name" url:"-"`
	Scopes         []CreatePlatformPracticeAPIKeyRequestScopesItem `json:"scopes,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreatePlatformPracticeAPIKeyRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyRequest) SetIdempotencyKey(idempotencyKey string) {
	c.IdempotencyKey = idempotencyKey
	c.require(createPlatformPracticeAPIKeyRequestFieldIdempotencyKey)
}

// SetPracticeID sets the PracticeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyRequest) SetPracticeID(practiceID string) {
	c.PracticeID = practiceID
	c.require(createPlatformPracticeAPIKeyRequestFieldPracticeID)
}

// SetAllowedIps sets the AllowedIps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyRequest) SetAllowedIps(allowedIps []string) {
	c.AllowedIps = allowedIps
	c.require(createPlatformPracticeAPIKeyRequestFieldAllowedIps)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyRequest) SetExpiresAt(expiresAt *string) {
	c.ExpiresAt = expiresAt
	c.require(createPlatformPracticeAPIKeyRequestFieldExpiresAt)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyRequest) SetName(name string) {
	c.Name = name
	c.require(createPlatformPracticeAPIKeyRequestFieldName)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyRequest) SetScopes(scopes []CreatePlatformPracticeAPIKeyRequestScopesItem) {
	c.Scopes = scopes
	c.require(createPlatformPracticeAPIKeyRequestFieldScopes)
}

func (c *CreatePlatformPracticeAPIKeyRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePlatformPracticeAPIKeyRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreatePlatformPracticeAPIKeyRequest(body)
	return nil
}

func (c *CreatePlatformPracticeAPIKeyRequest) MarshalJSON() ([]byte, error) {
	type embed CreatePlatformPracticeAPIKeyRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createPlatformPracticeAPIKeyResponseFieldAPIKey         = big.NewInt(1 << 0)
	createPlatformPracticeAPIKeyResponseFieldSecret         = big.NewInt(1 << 1)
	createPlatformPracticeAPIKeyResponseFieldServiceAccount = big.NewInt(1 << 2)
)

type CreatePlatformPracticeAPIKeyResponse struct {
	APIKey         *CreatePlatformPracticeAPIKeyResponseAPIKey         `json:"apiKey" url:"apiKey"`
	Secret         string                                              `json:"secret" url:"secret"`
	ServiceAccount *CreatePlatformPracticeAPIKeyResponseServiceAccount `json:"serviceAccount" url:"serviceAccount"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreatePlatformPracticeAPIKeyResponse) GetAPIKey() *CreatePlatformPracticeAPIKeyResponseAPIKey {
	if c == nil {
		return nil
	}
	return c.APIKey
}

func (c *CreatePlatformPracticeAPIKeyResponse) GetSecret() string {
	if c == nil {
		return ""
	}
	return c.Secret
}

func (c *CreatePlatformPracticeAPIKeyResponse) GetServiceAccount() *CreatePlatformPracticeAPIKeyResponseServiceAccount {
	if c == nil {
		return nil
	}
	return c.ServiceAccount
}

func (c *CreatePlatformPracticeAPIKeyResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreatePlatformPracticeAPIKeyResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAPIKey sets the APIKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponse) SetAPIKey(apiKey *CreatePlatformPracticeAPIKeyResponseAPIKey) {
	c.APIKey = apiKey
	c.require(createPlatformPracticeAPIKeyResponseFieldAPIKey)
}

// SetSecret sets the Secret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponse) SetSecret(secret string) {
	c.Secret = secret
	c.require(createPlatformPracticeAPIKeyResponseFieldSecret)
}

// SetServiceAccount sets the ServiceAccount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponse) SetServiceAccount(serviceAccount *CreatePlatformPracticeAPIKeyResponseServiceAccount) {
	c.ServiceAccount = serviceAccount
	c.require(createPlatformPracticeAPIKeyResponseFieldServiceAccount)
}

func (c *CreatePlatformPracticeAPIKeyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePlatformPracticeAPIKeyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreatePlatformPracticeAPIKeyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatePlatformPracticeAPIKeyResponse) MarshalJSON() ([]byte, error) {
	type embed CreatePlatformPracticeAPIKeyResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreatePlatformPracticeAPIKeyResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createPlatformPracticeAPIKeyResponseAPIKeyFieldAllowedIps = big.NewInt(1 << 0)
	createPlatformPracticeAPIKeyResponseAPIKeyFieldCreatedAt  = big.NewInt(1 << 1)
	createPlatformPracticeAPIKeyResponseAPIKeyFieldExpiresAt  = big.NewInt(1 << 2)
	createPlatformPracticeAPIKeyResponseAPIKeyFieldID         = big.NewInt(1 << 3)
	createPlatformPracticeAPIKeyResponseAPIKeyFieldKeyPrefix  = big.NewInt(1 << 4)
	createPlatformPracticeAPIKeyResponseAPIKeyFieldLastUsedAt = big.NewInt(1 << 5)
	createPlatformPracticeAPIKeyResponseAPIKeyFieldMode       = big.NewInt(1 << 6)
	createPlatformPracticeAPIKeyResponseAPIKeyFieldName       = big.NewInt(1 << 7)
	createPlatformPracticeAPIKeyResponseAPIKeyFieldRevokedAt  = big.NewInt(1 << 8)
	createPlatformPracticeAPIKeyResponseAPIKeyFieldScopes     = big.NewInt(1 << 9)
	createPlatformPracticeAPIKeyResponseAPIKeyFieldStatus     = big.NewInt(1 << 10)
)

type CreatePlatformPracticeAPIKeyResponseAPIKey struct {
	AllowedIps []string                                               `json:"allowedIps" url:"allowedIps"`
	CreatedAt  string                                                 `json:"createdAt" url:"createdAt"`
	ExpiresAt  *string                                                `json:"expiresAt,omitempty" url:"expiresAt,omitempty"`
	ID         string                                                 `json:"id" url:"id"`
	KeyPrefix  string                                                 `json:"keyPrefix" url:"keyPrefix"`
	LastUsedAt *string                                                `json:"lastUsedAt,omitempty" url:"lastUsedAt,omitempty"`
	Mode       CreatePlatformPracticeAPIKeyResponseAPIKeyMode         `json:"mode" url:"mode"`
	Name       string                                                 `json:"name" url:"name"`
	RevokedAt  *string                                                `json:"revokedAt,omitempty" url:"revokedAt,omitempty"`
	Scopes     []CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem `json:"scopes" url:"scopes"`
	Status     CreatePlatformPracticeAPIKeyResponseAPIKeyStatus       `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) GetAllowedIps() []string {
	if c == nil {
		return nil
	}
	return c.AllowedIps
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) GetExpiresAt() *string {
	if c == nil {
		return nil
	}
	return c.ExpiresAt
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) GetKeyPrefix() string {
	if c == nil {
		return ""
	}
	return c.KeyPrefix
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) GetLastUsedAt() *string {
	if c == nil {
		return nil
	}
	return c.LastUsedAt
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) GetMode() CreatePlatformPracticeAPIKeyResponseAPIKeyMode {
	if c == nil {
		return ""
	}
	return c.Mode
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) GetRevokedAt() *string {
	if c == nil {
		return nil
	}
	return c.RevokedAt
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) GetScopes() []CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem {
	if c == nil {
		return nil
	}
	return c.Scopes
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) GetStatus() CreatePlatformPracticeAPIKeyResponseAPIKeyStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAllowedIps sets the AllowedIps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) SetAllowedIps(allowedIps []string) {
	c.AllowedIps = allowedIps
	c.require(createPlatformPracticeAPIKeyResponseAPIKeyFieldAllowedIps)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) SetCreatedAt(createdAt string) {
	c.CreatedAt = createdAt
	c.require(createPlatformPracticeAPIKeyResponseAPIKeyFieldCreatedAt)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) SetExpiresAt(expiresAt *string) {
	c.ExpiresAt = expiresAt
	c.require(createPlatformPracticeAPIKeyResponseAPIKeyFieldExpiresAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) SetID(id string) {
	c.ID = id
	c.require(createPlatformPracticeAPIKeyResponseAPIKeyFieldID)
}

// SetKeyPrefix sets the KeyPrefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) SetKeyPrefix(keyPrefix string) {
	c.KeyPrefix = keyPrefix
	c.require(createPlatformPracticeAPIKeyResponseAPIKeyFieldKeyPrefix)
}

// SetLastUsedAt sets the LastUsedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) SetLastUsedAt(lastUsedAt *string) {
	c.LastUsedAt = lastUsedAt
	c.require(createPlatformPracticeAPIKeyResponseAPIKeyFieldLastUsedAt)
}

// SetMode sets the Mode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) SetMode(mode CreatePlatformPracticeAPIKeyResponseAPIKeyMode) {
	c.Mode = mode
	c.require(createPlatformPracticeAPIKeyResponseAPIKeyFieldMode)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) SetName(name string) {
	c.Name = name
	c.require(createPlatformPracticeAPIKeyResponseAPIKeyFieldName)
}

// SetRevokedAt sets the RevokedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) SetRevokedAt(revokedAt *string) {
	c.RevokedAt = revokedAt
	c.require(createPlatformPracticeAPIKeyResponseAPIKeyFieldRevokedAt)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) SetScopes(scopes []CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem) {
	c.Scopes = scopes
	c.require(createPlatformPracticeAPIKeyResponseAPIKeyFieldScopes)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) SetStatus(status CreatePlatformPracticeAPIKeyResponseAPIKeyStatus) {
	c.Status = status
	c.require(createPlatformPracticeAPIKeyResponseAPIKeyFieldStatus)
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePlatformPracticeAPIKeyResponseAPIKey
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreatePlatformPracticeAPIKeyResponseAPIKey(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) MarshalJSON() ([]byte, error) {
	type embed CreatePlatformPracticeAPIKeyResponseAPIKey
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreatePlatformPracticeAPIKeyResponseAPIKey) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreatePlatformPracticeAPIKeyResponseAPIKeyMode string

const (
	CreatePlatformPracticeAPIKeyResponseAPIKeyModeLive CreatePlatformPracticeAPIKeyResponseAPIKeyMode = "live"
	CreatePlatformPracticeAPIKeyResponseAPIKeyModeTest CreatePlatformPracticeAPIKeyResponseAPIKeyMode = "test"
)

func NewCreatePlatformPracticeAPIKeyResponseAPIKeyModeFromString(s string) (CreatePlatformPracticeAPIKeyResponseAPIKeyMode, error) {
	switch s {
	case "live":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyModeLive, nil
	case "test":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyModeTest, nil
	}
	var t CreatePlatformPracticeAPIKeyResponseAPIKeyMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePlatformPracticeAPIKeyResponseAPIKeyMode) Ptr() *CreatePlatformPracticeAPIKeyResponseAPIKeyMode {
	return &c
}

type CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem string

const (
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemCatalogRead              CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "catalog:read"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemSellingPricesRead        CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "selling_prices:read"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemSellingPricesWrite       CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "selling_prices:write"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemCatalogPricingRead       CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "catalog_pricing:read"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemCatalogPricingWrite      CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "catalog_pricing:write"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemFormulationDefaultsRead  CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "formulation_defaults:read"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemFormulationDefaultsWrite CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "formulation_defaults:write"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemPracticesRead            CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "practices:read"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemPracticesWrite           CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "practices:write"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemServiceKeysWrite         CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "service_keys:write"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemLocationsRead            CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "locations:read"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemLocationsWrite           CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "locations:write"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemOrdersRead               CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "orders:read"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemOrdersWrite              CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "orders:write"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemOrdersSign               CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "orders:sign"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemPatientsRead             CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "patients:read"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemPatientsWrite            CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "patients:write"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemTeamRead                 CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "team:read"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemTeamWrite                CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "team:write"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemHostedSessionsWrite      CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "hosted_sessions:write"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemWebhooksRead             CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "webhooks:read"
	CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemWebhooksWrite            CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem = "webhooks:write"
)

func NewCreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemFromString(s string) (CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem, error) {
	switch s {
	case "catalog:read":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemCatalogRead, nil
	case "selling_prices:read":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemSellingPricesRead, nil
	case "selling_prices:write":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemSellingPricesWrite, nil
	case "catalog_pricing:read":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemCatalogPricingRead, nil
	case "catalog_pricing:write":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemCatalogPricingWrite, nil
	case "formulation_defaults:read":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemFormulationDefaultsRead, nil
	case "formulation_defaults:write":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemFormulationDefaultsWrite, nil
	case "practices:read":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemPracticesRead, nil
	case "practices:write":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemPracticesWrite, nil
	case "service_keys:write":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemServiceKeysWrite, nil
	case "locations:read":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemLocationsRead, nil
	case "locations:write":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemLocationsWrite, nil
	case "orders:read":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemOrdersRead, nil
	case "orders:write":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemOrdersWrite, nil
	case "orders:sign":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemOrdersSign, nil
	case "patients:read":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemPatientsRead, nil
	case "patients:write":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemPatientsWrite, nil
	case "team:read":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemTeamRead, nil
	case "team:write":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemTeamWrite, nil
	case "hosted_sessions:write":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemHostedSessionsWrite, nil
	case "webhooks:read":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemWebhooksRead, nil
	case "webhooks:write":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItemWebhooksWrite, nil
	}
	var t CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem) Ptr() *CreatePlatformPracticeAPIKeyResponseAPIKeyScopesItem {
	return &c
}

type CreatePlatformPracticeAPIKeyResponseAPIKeyStatus string

const (
	CreatePlatformPracticeAPIKeyResponseAPIKeyStatusActive  CreatePlatformPracticeAPIKeyResponseAPIKeyStatus = "active"
	CreatePlatformPracticeAPIKeyResponseAPIKeyStatusExpired CreatePlatformPracticeAPIKeyResponseAPIKeyStatus = "expired"
	CreatePlatformPracticeAPIKeyResponseAPIKeyStatusRevoked CreatePlatformPracticeAPIKeyResponseAPIKeyStatus = "revoked"
)

func NewCreatePlatformPracticeAPIKeyResponseAPIKeyStatusFromString(s string) (CreatePlatformPracticeAPIKeyResponseAPIKeyStatus, error) {
	switch s {
	case "active":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyStatusActive, nil
	case "expired":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyStatusExpired, nil
	case "revoked":
		return CreatePlatformPracticeAPIKeyResponseAPIKeyStatusRevoked, nil
	}
	var t CreatePlatformPracticeAPIKeyResponseAPIKeyStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePlatformPracticeAPIKeyResponseAPIKeyStatus) Ptr() *CreatePlatformPracticeAPIKeyResponseAPIKeyStatus {
	return &c
}

var (
	createPlatformPracticeAPIKeyResponseServiceAccountFieldAPIVersion     = big.NewInt(1 << 0)
	createPlatformPracticeAPIKeyResponseServiceAccountFieldDisplayName    = big.NewInt(1 << 1)
	createPlatformPracticeAPIKeyResponseServiceAccountFieldID             = big.NewInt(1 << 2)
	createPlatformPracticeAPIKeyResponseServiceAccountFieldMaxScopes      = big.NewInt(1 << 3)
	createPlatformPracticeAPIKeyResponseServiceAccountFieldOrganizationID = big.NewInt(1 << 4)
	createPlatformPracticeAPIKeyResponseServiceAccountFieldStatus         = big.NewInt(1 << 5)
	createPlatformPracticeAPIKeyResponseServiceAccountFieldSubjectID      = big.NewInt(1 << 6)
	createPlatformPracticeAPIKeyResponseServiceAccountFieldSubjectType    = big.NewInt(1 << 7)
)

type CreatePlatformPracticeAPIKeyResponseServiceAccount struct {
	APIVersion     CreatePlatformPracticeAPIKeyResponseServiceAccountAPIVersion      `json:"apiVersion" url:"apiVersion"`
	DisplayName    string                                                            `json:"displayName" url:"displayName"`
	ID             string                                                            `json:"id" url:"id"`
	MaxScopes      []CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem `json:"maxScopes" url:"maxScopes"`
	OrganizationID string                                                            `json:"organizationId" url:"organizationId"`
	Status         CreatePlatformPracticeAPIKeyResponseServiceAccountStatus          `json:"status" url:"status"`
	SubjectID      string                                                            `json:"subjectId" url:"subjectId"`
	SubjectType    CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectType     `json:"subjectType" url:"subjectType"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) GetAPIVersion() CreatePlatformPracticeAPIKeyResponseServiceAccountAPIVersion {
	if c == nil {
		return ""
	}
	return c.APIVersion
}

func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}

func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) GetMaxScopes() []CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem {
	if c == nil {
		return nil
	}
	return c.MaxScopes
}

func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) GetOrganizationID() string {
	if c == nil {
		return ""
	}
	return c.OrganizationID
}

func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) GetStatus() CreatePlatformPracticeAPIKeyResponseServiceAccountStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) GetSubjectID() string {
	if c == nil {
		return ""
	}
	return c.SubjectID
}

func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) GetSubjectType() CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectType {
	if c == nil {
		return ""
	}
	return c.SubjectType
}

func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAPIVersion sets the APIVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) SetAPIVersion(apiVersion CreatePlatformPracticeAPIKeyResponseServiceAccountAPIVersion) {
	c.APIVersion = apiVersion
	c.require(createPlatformPracticeAPIKeyResponseServiceAccountFieldAPIVersion)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) SetDisplayName(displayName string) {
	c.DisplayName = displayName
	c.require(createPlatformPracticeAPIKeyResponseServiceAccountFieldDisplayName)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) SetID(id string) {
	c.ID = id
	c.require(createPlatformPracticeAPIKeyResponseServiceAccountFieldID)
}

// SetMaxScopes sets the MaxScopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) SetMaxScopes(maxScopes []CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem) {
	c.MaxScopes = maxScopes
	c.require(createPlatformPracticeAPIKeyResponseServiceAccountFieldMaxScopes)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) SetOrganizationID(organizationID string) {
	c.OrganizationID = organizationID
	c.require(createPlatformPracticeAPIKeyResponseServiceAccountFieldOrganizationID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) SetStatus(status CreatePlatformPracticeAPIKeyResponseServiceAccountStatus) {
	c.Status = status
	c.require(createPlatformPracticeAPIKeyResponseServiceAccountFieldStatus)
}

// SetSubjectID sets the SubjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) SetSubjectID(subjectID string) {
	c.SubjectID = subjectID
	c.require(createPlatformPracticeAPIKeyResponseServiceAccountFieldSubjectID)
}

// SetSubjectType sets the SubjectType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) SetSubjectType(subjectType CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectType) {
	c.SubjectType = subjectType
	c.require(createPlatformPracticeAPIKeyResponseServiceAccountFieldSubjectType)
}

func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePlatformPracticeAPIKeyResponseServiceAccount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreatePlatformPracticeAPIKeyResponseServiceAccount(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) MarshalJSON() ([]byte, error) {
	type embed CreatePlatformPracticeAPIKeyResponseServiceAccount
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreatePlatformPracticeAPIKeyResponseServiceAccount) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreatePlatformPracticeAPIKeyResponseServiceAccountAPIVersion string

const (
	CreatePlatformPracticeAPIKeyResponseServiceAccountAPIVersionTwoThousandTwentySix0928 CreatePlatformPracticeAPIKeyResponseServiceAccountAPIVersion = "2026-09-28"
)

func NewCreatePlatformPracticeAPIKeyResponseServiceAccountAPIVersionFromString(s string) (CreatePlatformPracticeAPIKeyResponseServiceAccountAPIVersion, error) {
	switch s {
	case "2026-09-28":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountAPIVersionTwoThousandTwentySix0928, nil
	}
	var t CreatePlatformPracticeAPIKeyResponseServiceAccountAPIVersion
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePlatformPracticeAPIKeyResponseServiceAccountAPIVersion) Ptr() *CreatePlatformPracticeAPIKeyResponseServiceAccountAPIVersion {
	return &c
}

type CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem string

const (
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemCatalogRead              CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "catalog:read"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemSellingPricesRead        CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "selling_prices:read"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemSellingPricesWrite       CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "selling_prices:write"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemCatalogPricingRead       CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "catalog_pricing:read"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemCatalogPricingWrite      CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "catalog_pricing:write"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemFormulationDefaultsRead  CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "formulation_defaults:read"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemFormulationDefaultsWrite CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "formulation_defaults:write"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemPracticesRead            CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "practices:read"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemPracticesWrite           CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "practices:write"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemServiceKeysWrite         CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "service_keys:write"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemLocationsRead            CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "locations:read"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemLocationsWrite           CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "locations:write"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemOrdersRead               CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "orders:read"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemOrdersWrite              CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "orders:write"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemOrdersSign               CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "orders:sign"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemPatientsRead             CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "patients:read"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemPatientsWrite            CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "patients:write"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemTeamRead                 CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "team:read"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemTeamWrite                CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "team:write"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemHostedSessionsWrite      CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "hosted_sessions:write"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemWebhooksRead             CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "webhooks:read"
	CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemWebhooksWrite            CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem = "webhooks:write"
)

func NewCreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemFromString(s string) (CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem, error) {
	switch s {
	case "catalog:read":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemCatalogRead, nil
	case "selling_prices:read":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemSellingPricesRead, nil
	case "selling_prices:write":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemSellingPricesWrite, nil
	case "catalog_pricing:read":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemCatalogPricingRead, nil
	case "catalog_pricing:write":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemCatalogPricingWrite, nil
	case "formulation_defaults:read":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemFormulationDefaultsRead, nil
	case "formulation_defaults:write":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemFormulationDefaultsWrite, nil
	case "practices:read":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemPracticesRead, nil
	case "practices:write":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemPracticesWrite, nil
	case "service_keys:write":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemServiceKeysWrite, nil
	case "locations:read":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemLocationsRead, nil
	case "locations:write":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemLocationsWrite, nil
	case "orders:read":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemOrdersRead, nil
	case "orders:write":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemOrdersWrite, nil
	case "orders:sign":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemOrdersSign, nil
	case "patients:read":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemPatientsRead, nil
	case "patients:write":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemPatientsWrite, nil
	case "team:read":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemTeamRead, nil
	case "team:write":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemTeamWrite, nil
	case "hosted_sessions:write":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemHostedSessionsWrite, nil
	case "webhooks:read":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemWebhooksRead, nil
	case "webhooks:write":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItemWebhooksWrite, nil
	}
	var t CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem) Ptr() *CreatePlatformPracticeAPIKeyResponseServiceAccountMaxScopesItem {
	return &c
}

type CreatePlatformPracticeAPIKeyResponseServiceAccountStatus string

const (
	CreatePlatformPracticeAPIKeyResponseServiceAccountStatusActive   CreatePlatformPracticeAPIKeyResponseServiceAccountStatus = "active"
	CreatePlatformPracticeAPIKeyResponseServiceAccountStatusDisabled CreatePlatformPracticeAPIKeyResponseServiceAccountStatus = "disabled"
)

func NewCreatePlatformPracticeAPIKeyResponseServiceAccountStatusFromString(s string) (CreatePlatformPracticeAPIKeyResponseServiceAccountStatus, error) {
	switch s {
	case "active":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountStatusActive, nil
	case "disabled":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountStatusDisabled, nil
	}
	var t CreatePlatformPracticeAPIKeyResponseServiceAccountStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePlatformPracticeAPIKeyResponseServiceAccountStatus) Ptr() *CreatePlatformPracticeAPIKeyResponseServiceAccountStatus {
	return &c
}

type CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectType string

const (
	CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectTypePractice        CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectType = "practice"
	CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectTypeInternalService CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectType = "internal_service"
	CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectTypePharmacy        CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectType = "pharmacy"
	CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectTypePlatform        CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectType = "platform"
	CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectTypeUser            CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectType = "user"
)

func NewCreatePlatformPracticeAPIKeyResponseServiceAccountSubjectTypeFromString(s string) (CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectType, error) {
	switch s {
	case "practice":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectTypePractice, nil
	case "internal_service":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectTypeInternalService, nil
	case "pharmacy":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectTypePharmacy, nil
	case "platform":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectTypePlatform, nil
	case "user":
		return CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectTypeUser, nil
	}
	var t CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectType) Ptr() *CreatePlatformPracticeAPIKeyResponseServiceAccountSubjectType {
	return &c
}

var (
	getAPIAccessResponseFieldAPIKey         = big.NewInt(1 << 0)
	getAPIAccessResponseFieldLivemode       = big.NewInt(1 << 1)
	getAPIAccessResponseFieldObject         = big.NewInt(1 << 2)
	getAPIAccessResponseFieldScopes         = big.NewInt(1 << 3)
	getAPIAccessResponseFieldServiceAccount = big.NewInt(1 << 4)
)

type GetAPIAccessResponse struct {
	APIKey         *GetAPIAccessResponseAPIKey         `json:"apiKey" url:"apiKey"`
	Livemode       bool                                `json:"livemode" url:"livemode"`
	Object         GetAPIAccessResponseObject          `json:"object" url:"object"`
	Scopes         []string                            `json:"scopes" url:"scopes"`
	ServiceAccount *GetAPIAccessResponseServiceAccount `json:"serviceAccount" url:"serviceAccount"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetAPIAccessResponse) GetAPIKey() *GetAPIAccessResponseAPIKey {
	if g == nil {
		return nil
	}
	return g.APIKey
}

func (g *GetAPIAccessResponse) GetLivemode() bool {
	if g == nil {
		return false
	}
	return g.Livemode
}

func (g *GetAPIAccessResponse) GetObject() GetAPIAccessResponseObject {
	if g == nil {
		return ""
	}
	return g.Object
}

func (g *GetAPIAccessResponse) GetScopes() []string {
	if g == nil {
		return nil
	}
	return g.Scopes
}

func (g *GetAPIAccessResponse) GetServiceAccount() *GetAPIAccessResponseServiceAccount {
	if g == nil {
		return nil
	}
	return g.ServiceAccount
}

func (g *GetAPIAccessResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetAPIAccessResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAPIKey sets the APIKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIAccessResponse) SetAPIKey(apiKey *GetAPIAccessResponseAPIKey) {
	g.APIKey = apiKey
	g.require(getAPIAccessResponseFieldAPIKey)
}

// SetLivemode sets the Livemode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIAccessResponse) SetLivemode(livemode bool) {
	g.Livemode = livemode
	g.require(getAPIAccessResponseFieldLivemode)
}

// SetObject sets the Object field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIAccessResponse) SetObject(object GetAPIAccessResponseObject) {
	g.Object = object
	g.require(getAPIAccessResponseFieldObject)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIAccessResponse) SetScopes(scopes []string) {
	g.Scopes = scopes
	g.require(getAPIAccessResponseFieldScopes)
}

// SetServiceAccount sets the ServiceAccount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIAccessResponse) SetServiceAccount(serviceAccount *GetAPIAccessResponseServiceAccount) {
	g.ServiceAccount = serviceAccount
	g.require(getAPIAccessResponseFieldServiceAccount)
}

func (g *GetAPIAccessResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetAPIAccessResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetAPIAccessResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetAPIAccessResponse) MarshalJSON() ([]byte, error) {
	type embed GetAPIAccessResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetAPIAccessResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getAPIAccessResponseAPIKeyFieldID        = big.NewInt(1 << 0)
	getAPIAccessResponseAPIKeyFieldKeyPrefix = big.NewInt(1 << 1)
	getAPIAccessResponseAPIKeyFieldObject    = big.NewInt(1 << 2)
)

type GetAPIAccessResponseAPIKey struct {
	ID        string                           `json:"id" url:"id"`
	KeyPrefix string                           `json:"keyPrefix" url:"keyPrefix"`
	Object    GetAPIAccessResponseAPIKeyObject `json:"object" url:"object"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetAPIAccessResponseAPIKey) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetAPIAccessResponseAPIKey) GetKeyPrefix() string {
	if g == nil {
		return ""
	}
	return g.KeyPrefix
}

func (g *GetAPIAccessResponseAPIKey) GetObject() GetAPIAccessResponseAPIKeyObject {
	if g == nil {
		return ""
	}
	return g.Object
}

func (g *GetAPIAccessResponseAPIKey) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetAPIAccessResponseAPIKey) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIAccessResponseAPIKey) SetID(id string) {
	g.ID = id
	g.require(getAPIAccessResponseAPIKeyFieldID)
}

// SetKeyPrefix sets the KeyPrefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIAccessResponseAPIKey) SetKeyPrefix(keyPrefix string) {
	g.KeyPrefix = keyPrefix
	g.require(getAPIAccessResponseAPIKeyFieldKeyPrefix)
}

// SetObject sets the Object field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIAccessResponseAPIKey) SetObject(object GetAPIAccessResponseAPIKeyObject) {
	g.Object = object
	g.require(getAPIAccessResponseAPIKeyFieldObject)
}

func (g *GetAPIAccessResponseAPIKey) UnmarshalJSON(data []byte) error {
	type unmarshaler GetAPIAccessResponseAPIKey
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetAPIAccessResponseAPIKey(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetAPIAccessResponseAPIKey) MarshalJSON() ([]byte, error) {
	type embed GetAPIAccessResponseAPIKey
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetAPIAccessResponseAPIKey) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetAPIAccessResponseAPIKeyObject string

const (
	GetAPIAccessResponseAPIKeyObjectAPIKey GetAPIAccessResponseAPIKeyObject = "api_key"
)

func NewGetAPIAccessResponseAPIKeyObjectFromString(s string) (GetAPIAccessResponseAPIKeyObject, error) {
	switch s {
	case "api_key":
		return GetAPIAccessResponseAPIKeyObjectAPIKey, nil
	}
	var t GetAPIAccessResponseAPIKeyObject
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetAPIAccessResponseAPIKeyObject) Ptr() *GetAPIAccessResponseAPIKeyObject {
	return &g
}

type GetAPIAccessResponseObject string

const (
	GetAPIAccessResponseObjectAPIAccess GetAPIAccessResponseObject = "api_access"
)

func NewGetAPIAccessResponseObjectFromString(s string) (GetAPIAccessResponseObject, error) {
	switch s {
	case "api_access":
		return GetAPIAccessResponseObjectAPIAccess, nil
	}
	var t GetAPIAccessResponseObject
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetAPIAccessResponseObject) Ptr() *GetAPIAccessResponseObject {
	return &g
}

var (
	getAPIAccessResponseServiceAccountFieldAPIVersion  = big.NewInt(1 << 0)
	getAPIAccessResponseServiceAccountFieldID          = big.NewInt(1 << 1)
	getAPIAccessResponseServiceAccountFieldObject      = big.NewInt(1 << 2)
	getAPIAccessResponseServiceAccountFieldSubjectID   = big.NewInt(1 << 3)
	getAPIAccessResponseServiceAccountFieldSubjectType = big.NewInt(1 << 4)
)

type GetAPIAccessResponseServiceAccount struct {
	APIVersion  GetAPIAccessResponseServiceAccountAPIVersion `json:"apiVersion" url:"apiVersion"`
	ID          string                                       `json:"id" url:"id"`
	Object      GetAPIAccessResponseServiceAccountObject     `json:"object" url:"object"`
	SubjectID   string                                       `json:"subjectId" url:"subjectId"`
	SubjectType string                                       `json:"subjectType" url:"subjectType"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetAPIAccessResponseServiceAccount) GetAPIVersion() GetAPIAccessResponseServiceAccountAPIVersion {
	if g == nil {
		return ""
	}
	return g.APIVersion
}

func (g *GetAPIAccessResponseServiceAccount) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetAPIAccessResponseServiceAccount) GetObject() GetAPIAccessResponseServiceAccountObject {
	if g == nil {
		return ""
	}
	return g.Object
}

func (g *GetAPIAccessResponseServiceAccount) GetSubjectID() string {
	if g == nil {
		return ""
	}
	return g.SubjectID
}

func (g *GetAPIAccessResponseServiceAccount) GetSubjectType() string {
	if g == nil {
		return ""
	}
	return g.SubjectType
}

func (g *GetAPIAccessResponseServiceAccount) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetAPIAccessResponseServiceAccount) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAPIVersion sets the APIVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIAccessResponseServiceAccount) SetAPIVersion(apiVersion GetAPIAccessResponseServiceAccountAPIVersion) {
	g.APIVersion = apiVersion
	g.require(getAPIAccessResponseServiceAccountFieldAPIVersion)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIAccessResponseServiceAccount) SetID(id string) {
	g.ID = id
	g.require(getAPIAccessResponseServiceAccountFieldID)
}

// SetObject sets the Object field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIAccessResponseServiceAccount) SetObject(object GetAPIAccessResponseServiceAccountObject) {
	g.Object = object
	g.require(getAPIAccessResponseServiceAccountFieldObject)
}

// SetSubjectID sets the SubjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIAccessResponseServiceAccount) SetSubjectID(subjectID string) {
	g.SubjectID = subjectID
	g.require(getAPIAccessResponseServiceAccountFieldSubjectID)
}

// SetSubjectType sets the SubjectType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIAccessResponseServiceAccount) SetSubjectType(subjectType string) {
	g.SubjectType = subjectType
	g.require(getAPIAccessResponseServiceAccountFieldSubjectType)
}

func (g *GetAPIAccessResponseServiceAccount) UnmarshalJSON(data []byte) error {
	type unmarshaler GetAPIAccessResponseServiceAccount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetAPIAccessResponseServiceAccount(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetAPIAccessResponseServiceAccount) MarshalJSON() ([]byte, error) {
	type embed GetAPIAccessResponseServiceAccount
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetAPIAccessResponseServiceAccount) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetAPIAccessResponseServiceAccountAPIVersion string

const (
	GetAPIAccessResponseServiceAccountAPIVersionTwoThousandTwentySix0928 GetAPIAccessResponseServiceAccountAPIVersion = "2026-09-28"
)

func NewGetAPIAccessResponseServiceAccountAPIVersionFromString(s string) (GetAPIAccessResponseServiceAccountAPIVersion, error) {
	switch s {
	case "2026-09-28":
		return GetAPIAccessResponseServiceAccountAPIVersionTwoThousandTwentySix0928, nil
	}
	var t GetAPIAccessResponseServiceAccountAPIVersion
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetAPIAccessResponseServiceAccountAPIVersion) Ptr() *GetAPIAccessResponseServiceAccountAPIVersion {
	return &g
}

type GetAPIAccessResponseServiceAccountObject string

const (
	GetAPIAccessResponseServiceAccountObjectServiceAccount GetAPIAccessResponseServiceAccountObject = "service_account"
)

func NewGetAPIAccessResponseServiceAccountObjectFromString(s string) (GetAPIAccessResponseServiceAccountObject, error) {
	switch s {
	case "service_account":
		return GetAPIAccessResponseServiceAccountObjectServiceAccount, nil
	}
	var t GetAPIAccessResponseServiceAccountObject
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetAPIAccessResponseServiceAccountObject) Ptr() *GetAPIAccessResponseServiceAccountObject {
	return &g
}

type CreatePlatformPracticeAPIKeyRequestScopesItem string

const (
	CreatePlatformPracticeAPIKeyRequestScopesItemCatalogRead              CreatePlatformPracticeAPIKeyRequestScopesItem = "catalog:read"
	CreatePlatformPracticeAPIKeyRequestScopesItemSellingPricesRead        CreatePlatformPracticeAPIKeyRequestScopesItem = "selling_prices:read"
	CreatePlatformPracticeAPIKeyRequestScopesItemSellingPricesWrite       CreatePlatformPracticeAPIKeyRequestScopesItem = "selling_prices:write"
	CreatePlatformPracticeAPIKeyRequestScopesItemCatalogPricingRead       CreatePlatformPracticeAPIKeyRequestScopesItem = "catalog_pricing:read"
	CreatePlatformPracticeAPIKeyRequestScopesItemCatalogPricingWrite      CreatePlatformPracticeAPIKeyRequestScopesItem = "catalog_pricing:write"
	CreatePlatformPracticeAPIKeyRequestScopesItemFormulationDefaultsRead  CreatePlatformPracticeAPIKeyRequestScopesItem = "formulation_defaults:read"
	CreatePlatformPracticeAPIKeyRequestScopesItemFormulationDefaultsWrite CreatePlatformPracticeAPIKeyRequestScopesItem = "formulation_defaults:write"
	CreatePlatformPracticeAPIKeyRequestScopesItemPracticesRead            CreatePlatformPracticeAPIKeyRequestScopesItem = "practices:read"
	CreatePlatformPracticeAPIKeyRequestScopesItemPracticesWrite           CreatePlatformPracticeAPIKeyRequestScopesItem = "practices:write"
	CreatePlatformPracticeAPIKeyRequestScopesItemServiceKeysWrite         CreatePlatformPracticeAPIKeyRequestScopesItem = "service_keys:write"
	CreatePlatformPracticeAPIKeyRequestScopesItemLocationsRead            CreatePlatformPracticeAPIKeyRequestScopesItem = "locations:read"
	CreatePlatformPracticeAPIKeyRequestScopesItemLocationsWrite           CreatePlatformPracticeAPIKeyRequestScopesItem = "locations:write"
	CreatePlatformPracticeAPIKeyRequestScopesItemOrdersRead               CreatePlatformPracticeAPIKeyRequestScopesItem = "orders:read"
	CreatePlatformPracticeAPIKeyRequestScopesItemOrdersWrite              CreatePlatformPracticeAPIKeyRequestScopesItem = "orders:write"
	CreatePlatformPracticeAPIKeyRequestScopesItemOrdersSign               CreatePlatformPracticeAPIKeyRequestScopesItem = "orders:sign"
	CreatePlatformPracticeAPIKeyRequestScopesItemPatientsRead             CreatePlatformPracticeAPIKeyRequestScopesItem = "patients:read"
	CreatePlatformPracticeAPIKeyRequestScopesItemPatientsWrite            CreatePlatformPracticeAPIKeyRequestScopesItem = "patients:write"
	CreatePlatformPracticeAPIKeyRequestScopesItemTeamRead                 CreatePlatformPracticeAPIKeyRequestScopesItem = "team:read"
	CreatePlatformPracticeAPIKeyRequestScopesItemTeamWrite                CreatePlatformPracticeAPIKeyRequestScopesItem = "team:write"
	CreatePlatformPracticeAPIKeyRequestScopesItemHostedSessionsWrite      CreatePlatformPracticeAPIKeyRequestScopesItem = "hosted_sessions:write"
	CreatePlatformPracticeAPIKeyRequestScopesItemWebhooksRead             CreatePlatformPracticeAPIKeyRequestScopesItem = "webhooks:read"
	CreatePlatformPracticeAPIKeyRequestScopesItemWebhooksWrite            CreatePlatformPracticeAPIKeyRequestScopesItem = "webhooks:write"
)

func NewCreatePlatformPracticeAPIKeyRequestScopesItemFromString(s string) (CreatePlatformPracticeAPIKeyRequestScopesItem, error) {
	switch s {
	case "catalog:read":
		return CreatePlatformPracticeAPIKeyRequestScopesItemCatalogRead, nil
	case "selling_prices:read":
		return CreatePlatformPracticeAPIKeyRequestScopesItemSellingPricesRead, nil
	case "selling_prices:write":
		return CreatePlatformPracticeAPIKeyRequestScopesItemSellingPricesWrite, nil
	case "catalog_pricing:read":
		return CreatePlatformPracticeAPIKeyRequestScopesItemCatalogPricingRead, nil
	case "catalog_pricing:write":
		return CreatePlatformPracticeAPIKeyRequestScopesItemCatalogPricingWrite, nil
	case "formulation_defaults:read":
		return CreatePlatformPracticeAPIKeyRequestScopesItemFormulationDefaultsRead, nil
	case "formulation_defaults:write":
		return CreatePlatformPracticeAPIKeyRequestScopesItemFormulationDefaultsWrite, nil
	case "practices:read":
		return CreatePlatformPracticeAPIKeyRequestScopesItemPracticesRead, nil
	case "practices:write":
		return CreatePlatformPracticeAPIKeyRequestScopesItemPracticesWrite, nil
	case "service_keys:write":
		return CreatePlatformPracticeAPIKeyRequestScopesItemServiceKeysWrite, nil
	case "locations:read":
		return CreatePlatformPracticeAPIKeyRequestScopesItemLocationsRead, nil
	case "locations:write":
		return CreatePlatformPracticeAPIKeyRequestScopesItemLocationsWrite, nil
	case "orders:read":
		return CreatePlatformPracticeAPIKeyRequestScopesItemOrdersRead, nil
	case "orders:write":
		return CreatePlatformPracticeAPIKeyRequestScopesItemOrdersWrite, nil
	case "orders:sign":
		return CreatePlatformPracticeAPIKeyRequestScopesItemOrdersSign, nil
	case "patients:read":
		return CreatePlatformPracticeAPIKeyRequestScopesItemPatientsRead, nil
	case "patients:write":
		return CreatePlatformPracticeAPIKeyRequestScopesItemPatientsWrite, nil
	case "team:read":
		return CreatePlatformPracticeAPIKeyRequestScopesItemTeamRead, nil
	case "team:write":
		return CreatePlatformPracticeAPIKeyRequestScopesItemTeamWrite, nil
	case "hosted_sessions:write":
		return CreatePlatformPracticeAPIKeyRequestScopesItemHostedSessionsWrite, nil
	case "webhooks:read":
		return CreatePlatformPracticeAPIKeyRequestScopesItemWebhooksRead, nil
	case "webhooks:write":
		return CreatePlatformPracticeAPIKeyRequestScopesItemWebhooksWrite, nil
	}
	var t CreatePlatformPracticeAPIKeyRequestScopesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePlatformPracticeAPIKeyRequestScopesItem) Ptr() *CreatePlatformPracticeAPIKeyRequestScopesItem {
	return &c
}
