// Code generated by Fern. DO NOT EDIT.

package batches

import (
	context "context"

	affinity "github.com/affinity-health/affinity-go"
	core "github.com/affinity-health/affinity-go/core"
	internal "github.com/affinity-health/affinity-go/internal"
	option "github.com/affinity-health/affinity-go/option"
	orders "github.com/affinity-health/affinity-go/orders"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Creates 1–20 orders for distinct patients in one practice, each with 1–20 prescriptions. Each accepts patientId or inline patient details. Orders and newly created patients commit atomically; any failure saves none. Requires orders:write and Idempotency-Key; inline patients also require patients:write. Omitted actor context defaults to the authenticated service account as a system actor. Sign and submit each resulting order separately using orders:sign.
func (c *Client) Create(
	ctx context.Context,
	request *orders.CreateOrderBatchRequest,
	opts ...option.RequestOption,
) (*affinity.CreateOrderBatchResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
