// Code generated by Fern. DO NOT EDIT.

package patients_allergies_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	client "github.com/affinity-health/affinity-go/client"
	option "github.com/affinity-health/affinity-go/option"
	patients "github.com/affinity-health/affinity-go/patients"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestPatientsAllergiesGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &patients.GetAllergiesRequest{
		PracticeID: "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		PatientID:  "pat_01j2y8m6jcc9tt24af5pw9x1bc",
	}
	_, invocationErr := client.Patients.Allergies.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPatientsAllergiesGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPatientsAllergiesGetWithWireMock", "GET", "/v1/practices/prac_01j2y8m6jcc9tt24af5pw9x1bc/patients/pat_01j2y8m6jcc9tt24af5pw9x1bc/allergies", nil, 1)
}

func TestPatientsAllergiesReplaceWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &patients.ReplacePatientAllergiesRequest{
		PracticeID:     "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		PatientID:      "pat_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
		Allergies: []*patients.ReplacePatientAllergiesRequestAllergiesItem{
			&patients.ReplacePatientAllergiesRequestAllergiesItem{
				Category: patients.ReplacePatientAllergiesRequestAllergiesItemCategoryDrug,
				Reactions: []*patients.ReplacePatientAllergiesRequestAllergiesItemReactionsItem{
					&patients.ReplacePatientAllergiesRequestAllergiesItemReactionsItem{
						Display: "display",
					},
				},
				Source:             patients.ReplacePatientAllergiesRequestAllergiesItemSourceDoctor,
				Substance:          "substance",
				VerificationStatus: patients.ReplacePatientAllergiesRequestAllergiesItemVerificationStatusUnconfirmed,
			},
		},
		ReviewStatus: patients.ReplacePatientAllergiesRequestReviewStatusNotReviewed,
	}
	_, invocationErr := client.Patients.Allergies.Replace(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPatientsAllergiesReplaceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPatientsAllergiesReplaceWithWireMock", "PUT", "/v1/practices/prac_01j2y8m6jcc9tt24af5pw9x1bc/patients/pat_01j2y8m6jcc9tt24af5pw9x1bc/allergies", nil, 1)
}
