// Code generated by Fern. DO NOT EDIT.

package catalog

import (
	context "context"

	affinity "github.com/affinity-health/affinity-go"
	core "github.com/affinity-health/affinity-go/core"
	internal "github.com/affinity-health/affinity-go/internal"
	option "github.com/affinity-health/affinity-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Lists catalog items for the authenticated account and mode. Use view=medications for priced prescription groups with offer counts, pharmacy counts, and strengths; the default view=offers returns individual offers. Use relatedToCatalogItemId to find offers for the same medication and route. When practiceId is supplied, a practice price overrides the platform price and missing overrides inherit the platform price.
func (c *Client) ListCatalogItems(
	ctx context.Context,
	request *affinity.ListCatalogItemsRequest,
	opts ...option.RequestOption,
) (*affinity.ListCatalogItemsResponse, error) {
	response, err := c.WithRawResponse.ListCatalogItems(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Lists pharmacies available to the authenticated account, including approved invite-only relationships.
func (c *Client) ListPharmacies(
	ctx context.Context,
	request *affinity.ListPharmaciesRequest,
	opts ...option.RequestOption,
) (*affinity.ListPharmaciesResponse, error) {
	response, err := c.WithRawResponse.ListPharmacies(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns an array of at most 50 reviewed shipping services eligible for a catalog item, destination, and API mode. destinationState must be a USPS state or territory code. Each option has one temperature; pharmacy catalog summaries list all supported temperatures.
func (c *Client) ListShippingOptions(
	ctx context.Context,
	request *affinity.ListShippingOptionsRequest,
	opts ...option.RequestOption,
) (affinity.ListShippingOptionsResponse, error) {
	response, err := c.WithRawResponse.ListShippingOptions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires catalog:read. Returns reviewed SIG presets, guided patterns, quantity constraints and product requirements for a practice and mode. Revisions identify changed defaults. No patient-specific rationale or diagnosis is inferred.
func (c *Client) RetrievePrescribingOptions(
	ctx context.Context,
	request *affinity.RetrievePrescribingOptionsRequest,
	opts ...option.RequestOption,
) (*affinity.RetrievePrescribingOptionsResponse, error) {
	response, err := c.WithRawResponse.RetrievePrescribingOptions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
