// Code generated by Fern. DO NOT EDIT.

package catalog

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersGetPrescribingOptionsRequest(t *testing.T) {
	t.Run("SetCatalogItemID", func(t *testing.T) {
		obj := &GetPrescribingOptionsRequest{}
		var fernTestValueCatalogItemID string
		obj.SetCatalogItemID(fernTestValueCatalogItemID)
		assert.Equal(t, fernTestValueCatalogItemID, obj.CatalogItemID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPracticeID", func(t *testing.T) {
		obj := &GetPrescribingOptionsRequest{}
		var fernTestValuePracticeID string
		obj.SetPracticeID(fernTestValuePracticeID)
		assert.Equal(t, fernTestValuePracticeID, obj.PracticeID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetPrescribingOptionsRequest(t *testing.T) {
	t.Run("SetCatalogItemID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPrescribingOptionsRequest{}
		var fernTestValueCatalogItemID string

		// Act
		obj.SetCatalogItemID(fernTestValueCatalogItemID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPracticeID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPrescribingOptionsRequest{}
		var fernTestValuePracticeID string

		// Act
		obj.SetPracticeID(fernTestValuePracticeID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}
