// Code generated by Fern. DO NOT EDIT.

package catalog

import (
	big "math/big"
)

var (
	getPrescribingOptionsRequestFieldCatalogItemID = big.NewInt(1 << 0)
	getPrescribingOptionsRequestFieldPracticeID    = big.NewInt(1 << 1)
)

type GetPrescribingOptionsRequest struct {
	CatalogItemID string `json:"-" url:"-"`
	PracticeID    string `json:"-" url:"practiceId"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPrescribingOptionsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCatalogItemID sets the CatalogItemID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrescribingOptionsRequest) SetCatalogItemID(catalogItemID string) {
	g.CatalogItemID = catalogItemID
	g.require(getPrescribingOptionsRequestFieldCatalogItemID)
}

// SetPracticeID sets the PracticeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrescribingOptionsRequest) SetPracticeID(practiceID string) {
	g.PracticeID = practiceID
	g.require(getPrescribingOptionsRequestFieldPracticeID)
}
