// Code generated by Fern. DO NOT EDIT.

package orders_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	affinity "github.com/affinity-health/affinity-go"
	client "github.com/affinity-health/affinity-go/client"
	option "github.com/affinity-health/affinity-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestOrdersListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.ListOrdersRequest{
		EndingBefore: affinity.String(
			"ord_01j2y8m6jcc9tt24af5pw9x1bc",
		),
		OrderID: affinity.String(
			"ord_01j2y8m6jcc9tt24af5pw9x1bc",
		),
		PatientID: affinity.String(
			"pat_01j2y8m6jcc9tt24af5pw9x1bc",
		),
		PracticeID: affinity.String(
			"prac_01j2y8m6jcc9tt24af5pw9x1bc",
		),
		StartingAfter: affinity.String(
			"ord_01j2y8m6jcc9tt24af5pw9x1bc",
		),
	}
	_, invocationErr := client.Orders.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrdersListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrdersListWithWireMock", "GET", "/v1/orders", map[string]interface{}{"endingBefore": "ord_01j2y8m6jcc9tt24af5pw9x1bc", "orderId": "ord_01j2y8m6jcc9tt24af5pw9x1bc", "patientId": "pat_01j2y8m6jcc9tt24af5pw9x1bc", "practiceId": "prac_01j2y8m6jcc9tt24af5pw9x1bc", "startingAfter": "ord_01j2y8m6jcc9tt24af5pw9x1bc"}, 1)
}

func TestOrdersCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.CreateOrderRequest{
		IdempotencyKey: "Idempotency-Key",
		PracticeID:     "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		Prescriptions: []*affinity.CreateOrderRequestPrescriptionsItem{
			&affinity.CreateOrderRequestPrescriptionsItem{
				DaysSupply:   1,
				Dispensing:   &affinity.CreateOrderRequestPrescriptionsItemDispensing{},
				Directions:   "directions",
				MedicationID: "cat_01j2y8m6jcc9tt24af5pw9x1bc",
				Quantity: &affinity.CreateOrderRequestPrescriptionsItemQuantity{
					CreateOrderRequestPrescriptionsItemQuantityOne: affinity.CreateOrderRequestPrescriptionsItemQuantityOneInfinity,
				},
				QuantityUnit: "quantityUnit",
				Refills:      1,
			},
		},
	}
	_, invocationErr := client.Orders.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrdersCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrdersCreateWithWireMock", "POST", "/v1/orders", nil, 1)
}

func TestOrdersGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.GetOrdersRequest{
		OrderID: "ord_01j2y8m6jcc9tt24af5pw9x1bc",
	}
	_, invocationErr := client.Orders.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrdersGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrdersGetWithWireMock", "GET", "/v1/orders/ord_01j2y8m6jcc9tt24af5pw9x1bc", nil, 1)
}

func TestOrdersCancelWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.CancelOrderRequest{
		OrderID:        "ord_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
		Reason:         "reason",
	}
	_, invocationErr := client.Orders.Cancel(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrdersCancelWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrdersCancelWithWireMock", "POST", "/v1/orders/ord_01j2y8m6jcc9tt24af5pw9x1bc/cancel", nil, 1)
}

func TestOrdersPreviewWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.PreviewOrderRequest{
		PracticeID: "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		Prescriptions: []*affinity.PreviewOrderRequestPrescriptionsItem{
			&affinity.PreviewOrderRequestPrescriptionsItem{
				MedicationID: "cat_01j2y8m6jcc9tt24af5pw9x1bc",
			},
		},
	}
	_, invocationErr := client.Orders.Preview(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrdersPreviewWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrdersPreviewWithWireMock", "POST", "/v1/order-previews", nil, 1)
}

func TestOrdersSignWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.SignOrderRequest{
		OrderID:              "ord_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey:       "Idempotency-Key",
		PracticeID:           "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		SignatureAttestation: true,
	}
	_, invocationErr := client.Orders.Sign(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrdersSignWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrdersSignWithWireMock", "POST", "/v1/orders/ord_01j2y8m6jcc9tt24af5pw9x1bc/sign", nil, 1)
}

func TestOrdersSignAndSubmitWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.SignAndSubmitOrderRequest{
		OrderID:              "ord_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey:       "Idempotency-Key",
		PracticeID:           "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		SignatureAttestation: true,
	}
	_, invocationErr := client.Orders.SignAndSubmit(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrdersSignAndSubmitWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrdersSignAndSubmitWithWireMock", "POST", "/v1/orders/ord_01j2y8m6jcc9tt24af5pw9x1bc/sign-and-submit", nil, 1)
}

func TestOrdersSubmitWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.SubmitOrderRequest{
		OrderID:        "ord_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
		PracticeID:     "prac_01j2y8m6jcc9tt24af5pw9x1bc",
	}
	_, invocationErr := client.Orders.Submit(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrdersSubmitWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrdersSubmitWithWireMock", "POST", "/v1/orders/ord_01j2y8m6jcc9tt24af5pw9x1bc/submit", nil, 1)
}

func TestOrdersRejectWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.RejectOrderRequest{
		OrderID:        "ord_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
		PracticeID:     "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		Reason:         "reason",
	}
	_, invocationErr := client.Orders.Reject(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrdersRejectWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrdersRejectWithWireMock", "POST", "/v1/orders/ord_01j2y8m6jcc9tt24af5pw9x1bc/rejection", nil, 1)
}
