// Code generated by Fern. DO NOT EDIT.

package team_invitations_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	affinity "github.com/affinity-health/affinity-go"
	client "github.com/affinity-health/affinity-go/client"
	option "github.com/affinity-health/affinity-go/option"
	team "github.com/affinity-health/affinity-go/team"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestTeamInvitationsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &team.ListInvitationsRequest{
		PracticeID: "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		StartingAfter: affinity.String(
			"invite_01j2y8m6jcc9tt24af5pw9x1bc",
		),
		EndingBefore: affinity.String(
			"invite_01j2y8m6jcc9tt24af5pw9x1bc",
		),
	}
	_, invocationErr := client.Team.Invitations.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTeamInvitationsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTeamInvitationsListWithWireMock", "GET", "/v1/practices/prac_01j2y8m6jcc9tt24af5pw9x1bc/team/invitations", map[string]interface{}{"startingAfter": "invite_01j2y8m6jcc9tt24af5pw9x1bc", "endingBefore": "invite_01j2y8m6jcc9tt24af5pw9x1bc"}, 1)
}

func TestTeamInvitationsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &team.InvitePracticeTeamPersonRequest{
		PracticeID:     "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
		ExternalID:     "externalId",
		Email:          "email",
		Name:           "name",
	}
	_, invocationErr := client.Team.Invitations.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTeamInvitationsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTeamInvitationsCreateWithWireMock", "POST", "/v1/practices/prac_01j2y8m6jcc9tt24af5pw9x1bc/team/invitations", nil, 1)
}

func TestTeamInvitationsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &team.GetInvitationsRequest{
		PracticeID:   "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		InvitationID: "invite_01j2y8m6jcc9tt24af5pw9x1bc",
	}
	_, invocationErr := client.Team.Invitations.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTeamInvitationsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTeamInvitationsGetWithWireMock", "GET", "/v1/practices/prac_01j2y8m6jcc9tt24af5pw9x1bc/team/invitations/invite_01j2y8m6jcc9tt24af5pw9x1bc", nil, 1)
}

func TestTeamInvitationsRevokeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &team.RevokeInvitationsRequest{
		PracticeID:     "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		InvitationID:   "invite_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
	}
	_, invocationErr := client.Team.Invitations.Revoke(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTeamInvitationsRevokeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTeamInvitationsRevokeWithWireMock", "DELETE", "/v1/practices/prac_01j2y8m6jcc9tt24af5pw9x1bc/team/invitations/invite_01j2y8m6jcc9tt24af5pw9x1bc", nil, 1)
}

func TestTeamInvitationsResendWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &team.ResendInvitationsRequest{
		PracticeID:     "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		InvitationID:   "invite_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
	}
	_, invocationErr := client.Team.Invitations.Resend(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTeamInvitationsResendWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTeamInvitationsResendWithWireMock", "POST", "/v1/practices/prac_01j2y8m6jcc9tt24af5pw9x1bc/team/invitations/invite_01j2y8m6jcc9tt24af5pw9x1bc/resend", nil, 1)
}
