// Code generated by Fern. DO NOT EDIT.

package webhooks_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	affinity "github.com/affinity-health/affinity-go"
	client "github.com/affinity-health/affinity-go/client"
	option "github.com/affinity-health/affinity-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestWebhooksListWebhookEndpointsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.ListWebhookEndpointsRequest{
		EndingBefore: affinity.String(
			"whe_01j2y8m6jcc9tt24af5pw9x1bc",
		),
		StartingAfter: affinity.String(
			"whe_01j2y8m6jcc9tt24af5pw9x1bc",
		),
	}
	_, invocationErr := client.Webhooks.ListWebhookEndpoints(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksListWebhookEndpointsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksListWebhookEndpointsWithWireMock", "GET", "/v1/webhook-endpoints", map[string]interface{}{"endingBefore": "whe_01j2y8m6jcc9tt24af5pw9x1bc", "startingAfter": "whe_01j2y8m6jcc9tt24af5pw9x1bc"}, 1)
}

func TestWebhooksCreateWebhookEndpointWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.CreateWebhookEndpointRequest{
		IdempotencyKey: "Idempotency-Key",
		URL:            "url",
	}
	_, invocationErr := client.Webhooks.CreateWebhookEndpoint(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksCreateWebhookEndpointWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksCreateWebhookEndpointWithWireMock", "POST", "/v1/webhook-endpoints", nil, 1)
}

func TestWebhooksDeleteWebhookEndpointWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.DeleteWebhookEndpointRequest{
		EndpointID:     "whe_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
	}
	_, invocationErr := client.Webhooks.DeleteWebhookEndpoint(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksDeleteWebhookEndpointWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksDeleteWebhookEndpointWithWireMock", "DELETE", "/v1/webhook-endpoints/whe_01j2y8m6jcc9tt24af5pw9x1bc", nil, 1)
}

func TestWebhooksUpdateWebhookEndpointWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.UpdateWebhookEndpointRequest{
		EndpointID:     "whe_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
	}
	_, invocationErr := client.Webhooks.UpdateWebhookEndpoint(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksUpdateWebhookEndpointWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksUpdateWebhookEndpointWithWireMock", "PATCH", "/v1/webhook-endpoints/whe_01j2y8m6jcc9tt24af5pw9x1bc", nil, 1)
}

func TestWebhooksRotateWebhookEndpointSecretWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.RotateWebhookEndpointSecretRequest{
		EndpointID:     "whe_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
	}
	_, invocationErr := client.Webhooks.RotateWebhookEndpointSecret(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksRotateWebhookEndpointSecretWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksRotateWebhookEndpointSecretWithWireMock", "POST", "/v1/webhook-endpoints/whe_01j2y8m6jcc9tt24af5pw9x1bc/rotate-secret", nil, 1)
}

func TestWebhooksTestWebhookEndpointWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.TestWebhookEndpointRequest{
		EndpointID:     "whe_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
	}
	_, invocationErr := client.Webhooks.TestWebhookEndpoint(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksTestWebhookEndpointWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksTestWebhookEndpointWithWireMock", "POST", "/v1/webhook-endpoints/whe_01j2y8m6jcc9tt24af5pw9x1bc/test", nil, 1)
}

func TestWebhooksListWebhookEventsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.ListWebhookEventsRequest{
		EndingBefore: affinity.String(
			"evt_01j2y8m6jcc9tt24af5pw9x1bc",
		),
		StartingAfter: affinity.String(
			"evt_01j2y8m6jcc9tt24af5pw9x1bc",
		),
	}
	_, invocationErr := client.Webhooks.ListWebhookEvents(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksListWebhookEventsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksListWebhookEventsWithWireMock", "GET", "/v1/webhook-events", map[string]interface{}{"endingBefore": "evt_01j2y8m6jcc9tt24af5pw9x1bc", "startingAfter": "evt_01j2y8m6jcc9tt24af5pw9x1bc"}, 1)
}

func TestWebhooksGetWebhookEventWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.GetWebhookEventRequest{
		EventID: "evt_01j2y8m6jcc9tt24af5pw9x1bc",
	}
	_, invocationErr := client.Webhooks.GetWebhookEvent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksGetWebhookEventWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksGetWebhookEventWithWireMock", "GET", "/v1/webhook-events/evt_01j2y8m6jcc9tt24af5pw9x1bc", nil, 1)
}

func TestWebhooksReplayWebhookEventWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.ReplayWebhookEventRequest{
		EventID:        "evt_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
	}
	_, invocationErr := client.Webhooks.ReplayWebhookEvent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksReplayWebhookEventWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksReplayWebhookEventWithWireMock", "POST", "/v1/webhook-events/evt_01j2y8m6jcc9tt24af5pw9x1bc/replay", nil, 1)
}

func TestWebhooksListWebhookGrantsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.ListWebhookGrantsRequest{
		StartingAfter: affinity.String(
			"acct_01j2y8m6jcc9tt24af5pw9x1bc",
		),
		EndingBefore: affinity.String(
			"acct_01j2y8m6jcc9tt24af5pw9x1bc",
		),
	}
	_, invocationErr := client.Webhooks.ListWebhookGrants(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksListWebhookGrantsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksListWebhookGrantsWithWireMock", "GET", "/v1/webhook-grants", map[string]interface{}{"startingAfter": "acct_01j2y8m6jcc9tt24af5pw9x1bc", "endingBefore": "acct_01j2y8m6jcc9tt24af5pw9x1bc"}, 1)
}

func TestWebhooksSaveWebhookGrantWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.SaveWebhookGrantRequest{
		PlatformID:     "acct_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
		Scopes: []affinity.SaveWebhookGrantRequestScopesItem{
			affinity.SaveWebhookGrantRequestScopesItemWebhooksRead,
		},
	}
	_, invocationErr := client.Webhooks.SaveWebhookGrant(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksSaveWebhookGrantWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksSaveWebhookGrantWithWireMock", "PUT", "/v1/webhook-grants/acct_01j2y8m6jcc9tt24af5pw9x1bc", nil, 1)
}

func TestWebhooksRevokeWebhookGrantWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &affinity.RevokeWebhookGrantRequest{
		PlatformID:     "acct_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
	}
	_, invocationErr := client.Webhooks.RevokeWebhookGrant(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksRevokeWebhookGrantWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksRevokeWebhookGrantWithWireMock", "DELETE", "/v1/webhook-grants/acct_01j2y8m6jcc9tt24af5pw9x1bc", nil, 1)
}
