// Code generated by Fern. DO NOT EDIT.

package client

import (
	items "github.com/affinity-health/affinity-go/catalog/items"
	prescribingoptions "github.com/affinity-health/affinity-go/catalog/prescribingoptions"
	sellingprices "github.com/affinity-health/affinity-go/catalog/sellingprices"
	shippingoptions "github.com/affinity-health/affinity-go/catalog/shippingoptions"
	core "github.com/affinity-health/affinity-go/core"
	internal "github.com/affinity-health/affinity-go/internal"
)

type Client struct {
	Items              *items.Client
	ShippingOptions    *shippingoptions.Client
	PrescribingOptions *prescribingoptions.Client
	SellingPrices      *sellingprices.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Items:              items.NewClient(options),
		ShippingOptions:    shippingoptions.NewClient(options),
		PrescribingOptions: prescribingoptions.NewClient(options),
		SellingPrices:      sellingprices.NewClient(options),
		options:            options,
		baseURL:            options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
