// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/affinity-health/affinity-go/core"
	internal "github.com/affinity-health/affinity-go/internal"
	endpoints "github.com/affinity-health/affinity-go/webhooks/endpoints"
	events "github.com/affinity-health/affinity-go/webhooks/events"
	grants "github.com/affinity-health/affinity-go/webhooks/grants"
)

type Client struct {
	Endpoints *endpoints.Client
	Events    *events.Client
	Grants    *grants.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Endpoints: endpoints.NewClient(options),
		Events:    events.NewClient(options),
		Grants:    grants.NewClient(options),
		options:   options,
		baseURL:   options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
