// Code generated by Fern. DO NOT EDIT.

package grants

import (
	context "context"

	affinity "github.com/affinity-health/affinity-go"
	core "github.com/affinity-health/affinity-go/core"
	internal "github.com/affinity-health/affinity-go/internal"
	option "github.com/affinity-health/affinity-go/option"
	webhooks "github.com/affinity-health/affinity-go/webhooks"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Requires webhooks:read on the owning practice or pharmacy key. Lists platform webhook grants in the key's mode. Platforms cannot list or grant themselves delegated access.
func (c *Client) List(
	ctx context.Context,
	request *webhooks.ListGrantsRequest,
	opts ...option.RequestOption,
) (*affinity.ListWebhookGrantsResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires webhooks:write on the owning practice or pharmacy key and Idempotency-Key. Grants or replaces a platform's webhook permissions in this mode. A practice must already be connected to that platform. The grant does not give the platform access to other API resources.
func (c *Client) Save(
	ctx context.Context,
	request *webhooks.SaveWebhookGrantRequest,
	opts ...option.RequestOption,
) (*affinity.SaveWebhookGrantResponse, error) {
	response, err := c.WithRawResponse.Save(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires webhooks:write on the owning practice or pharmacy key and Idempotency-Key. Removes platform webhook access in this mode. Existing endpoints remain owned by the practice or pharmacy and continue operating.
func (c *Client) Revoke(
	ctx context.Context,
	request *webhooks.RevokeGrantsRequest,
	opts ...option.RequestOption,
) (*affinity.RevokeWebhookGrantResponse, error) {
	response, err := c.WithRawResponse.Revoke(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
