// Code generated by Fern. DO NOT EDIT.

package locations

import (
	context "context"
	http "net/http"

	affinity "github.com/affinity-health/affinity-go"
	core "github.com/affinity-health/affinity-go/core"
	internal "github.com/affinity-health/affinity-go/internal"
	option "github.com/affinity-health/affinity-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListPracticeLocations(
	ctx context.Context,
	request *affinity.ListPracticeLocationsRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.ListPracticeLocationsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/locations",
		request.PracticeID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *affinity.ListPracticeLocationsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.ListPracticeLocationsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreatePracticeLocation(
	ctx context.Context,
	request *affinity.CreatePracticeLocationRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.CreatePracticeLocationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/locations",
		request.PracticeID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	headers.Add("Content-Type", "application/json")
	var response *affinity.CreatePracticeLocationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.CreatePracticeLocationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetPracticeLocation(
	ctx context.Context,
	request *affinity.GetPracticeLocationRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.GetPracticeLocationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/locations/%v",
		request.PracticeID,
		request.LocationID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *affinity.GetPracticeLocationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.GetPracticeLocationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdatePracticeLocation(
	ctx context.Context,
	request *affinity.UpdatePracticeLocationRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.UpdatePracticeLocationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/locations/%v",
		request.PracticeID,
		request.LocationID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	headers.Add("Content-Type", "application/json")
	var response *affinity.UpdatePracticeLocationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.UpdatePracticeLocationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ArchivePracticeLocation(
	ctx context.Context,
	request *affinity.ArchivePracticeLocationRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.ArchivePracticeLocationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/locations/%v/archive",
		request.PracticeID,
		request.LocationID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	var response *affinity.ArchivePracticeLocationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.ArchivePracticeLocationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
