// Code generated by Fern. DO NOT EDIT.

package orders_prescriptions_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	client "github.com/affinity-health/affinity-go/client"
	option "github.com/affinity-health/affinity-go/option"
	orders "github.com/affinity-health/affinity-go/orders"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestOrdersPrescriptionsAddWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &orders.AddOrderPrescriptionRequest{
		OrderID:        "ord_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
		PracticeID:     "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		Prescription: &orders.AddOrderPrescriptionRequestPrescription{
			DaysSupply:   1,
			Dispensing:   &orders.AddOrderPrescriptionRequestPrescriptionDispensing{},
			Directions:   "directions",
			MedicationID: "cat_01j2y8m6jcc9tt24af5pw9x1bc",
			Quantity: &orders.AddOrderPrescriptionRequestPrescriptionQuantity{
				AddOrderPrescriptionRequestPrescriptionQuantityOne: orders.AddOrderPrescriptionRequestPrescriptionQuantityOneInfinity,
			},
			QuantityUnit: "quantityUnit",
			Refills:      1,
		},
	}
	_, invocationErr := client.Orders.Prescriptions.Add(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrdersPrescriptionsAddWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrdersPrescriptionsAddWithWireMock", "POST", "/v1/orders/ord_01j2y8m6jcc9tt24af5pw9x1bc/prescriptions", nil, 1)
}

func TestOrdersPrescriptionsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &orders.UpdateOrderPrescriptionRequest{
		OrderID:        "ord_01j2y8m6jcc9tt24af5pw9x1bc",
		PrescriptionID: "rx_01j2y8m6jcc9tt24af5pw9x1bc",
		IdempotencyKey: "Idempotency-Key",
		PracticeID:     "prac_01j2y8m6jcc9tt24af5pw9x1bc",
		Prescription: &orders.UpdateOrderPrescriptionRequestPrescription{
			DaysSupply:   1,
			Dispensing:   &orders.UpdateOrderPrescriptionRequestPrescriptionDispensing{},
			Directions:   "directions",
			MedicationID: "cat_01j2y8m6jcc9tt24af5pw9x1bc",
			Quantity: &orders.UpdateOrderPrescriptionRequestPrescriptionQuantity{
				UpdateOrderPrescriptionRequestPrescriptionQuantityOne: orders.UpdateOrderPrescriptionRequestPrescriptionQuantityOneInfinity,
			},
			QuantityUnit: "quantityUnit",
			Refills:      1,
		},
	}
	_, invocationErr := client.Orders.Prescriptions.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrdersPrescriptionsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrdersPrescriptionsUpdateWithWireMock", "PATCH", "/v1/orders/ord_01j2y8m6jcc9tt24af5pw9x1bc/prescriptions/rx_01j2y8m6jcc9tt24af5pw9x1bc", nil, 1)
}
