// Code generated by Fern. DO NOT EDIT.

package patients

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersArchiveAddressesRequest(t *testing.T) {
	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &ArchiveAddressesRequest{}
		var fernTestValueIdempotencyKey *string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAffinityActorID", func(t *testing.T) {
		obj := &ArchiveAddressesRequest{}
		var fernTestValueAffinityActorID *string
		obj.SetAffinityActorID(fernTestValueAffinityActorID)
		assert.Equal(t, fernTestValueAffinityActorID, obj.AffinityActorID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAffinityActorType", func(t *testing.T) {
		obj := &ArchiveAddressesRequest{}
		var fernTestValueAffinityActorType *string
		obj.SetAffinityActorType(fernTestValueAffinityActorType)
		assert.Equal(t, fernTestValueAffinityActorType, obj.AffinityActorType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPracticeID", func(t *testing.T) {
		obj := &ArchiveAddressesRequest{}
		var fernTestValuePracticeID string
		obj.SetPracticeID(fernTestValuePracticeID)
		assert.Equal(t, fernTestValuePracticeID, obj.PracticeID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPatientID", func(t *testing.T) {
		obj := &ArchiveAddressesRequest{}
		var fernTestValuePatientID string
		obj.SetPatientID(fernTestValuePatientID)
		assert.Equal(t, fernTestValuePatientID, obj.PatientID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAddressID", func(t *testing.T) {
		obj := &ArchiveAddressesRequest{}
		var fernTestValueAddressID string
		obj.SetAddressID(fernTestValueAddressID)
		assert.Equal(t, fernTestValueAddressID, obj.AddressID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitArchiveAddressesRequest(t *testing.T) {
	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ArchiveAddressesRequest{}
		var fernTestValueIdempotencyKey *string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAffinityActorID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ArchiveAddressesRequest{}
		var fernTestValueAffinityActorID *string

		// Act
		obj.SetAffinityActorID(fernTestValueAffinityActorID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAffinityActorType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ArchiveAddressesRequest{}
		var fernTestValueAffinityActorType *string

		// Act
		obj.SetAffinityActorType(fernTestValueAffinityActorType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPracticeID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ArchiveAddressesRequest{}
		var fernTestValuePracticeID string

		// Act
		obj.SetPracticeID(fernTestValuePracticeID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPatientID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ArchiveAddressesRequest{}
		var fernTestValuePatientID string

		// Act
		obj.SetPatientID(fernTestValuePatientID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAddressID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ArchiveAddressesRequest{}
		var fernTestValueAddressID string

		// Act
		obj.SetAddressID(fernTestValueAddressID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreatePatientAddressRequest(t *testing.T) {
	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &CreatePatientAddressRequest{}
		var fernTestValueIdempotencyKey *string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAffinityActorID", func(t *testing.T) {
		obj := &CreatePatientAddressRequest{}
		var fernTestValueAffinityActorID *string
		obj.SetAffinityActorID(fernTestValueAffinityActorID)
		assert.Equal(t, fernTestValueAffinityActorID, obj.AffinityActorID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAffinityActorType", func(t *testing.T) {
		obj := &CreatePatientAddressRequest{}
		var fernTestValueAffinityActorType *string
		obj.SetAffinityActorType(fernTestValueAffinityActorType)
		assert.Equal(t, fernTestValueAffinityActorType, obj.AffinityActorType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPracticeID", func(t *testing.T) {
		obj := &CreatePatientAddressRequest{}
		var fernTestValuePracticeID string
		obj.SetPracticeID(fernTestValuePracticeID)
		assert.Equal(t, fernTestValuePracticeID, obj.PracticeID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPatientID", func(t *testing.T) {
		obj := &CreatePatientAddressRequest{}
		var fernTestValuePatientID string
		obj.SetPatientID(fernTestValuePatientID)
		assert.Equal(t, fernTestValuePatientID, obj.PatientID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAddress", func(t *testing.T) {
		obj := &CreatePatientAddressRequest{}
		var fernTestValueAddress *CreatePatientAddressRequestAddress
		obj.SetAddress(fernTestValueAddress)
		assert.Equal(t, fernTestValueAddress, obj.Address)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLabel", func(t *testing.T) {
		obj := &CreatePatientAddressRequest{}
		var fernTestValueLabel *string
		obj.SetLabel(fernTestValueLabel)
		assert.Equal(t, fernTestValueLabel, obj.Label)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPreferredShipping", func(t *testing.T) {
		obj := &CreatePatientAddressRequest{}
		var fernTestValuePreferredShipping *bool
		obj.SetPreferredShipping(fernTestValuePreferredShipping)
		assert.Equal(t, fernTestValuePreferredShipping, obj.PreferredShipping)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRecipientName", func(t *testing.T) {
		obj := &CreatePatientAddressRequest{}
		var fernTestValueRecipientName *string
		obj.SetRecipientName(fernTestValueRecipientName)
		assert.Equal(t, fernTestValueRecipientName, obj.RecipientName)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreatePatientAddressRequest(t *testing.T) {
	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequest{}
		var fernTestValueIdempotencyKey *string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAffinityActorID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequest{}
		var fernTestValueAffinityActorID *string

		// Act
		obj.SetAffinityActorID(fernTestValueAffinityActorID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAffinityActorType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequest{}
		var fernTestValueAffinityActorType *string

		// Act
		obj.SetAffinityActorType(fernTestValueAffinityActorType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPracticeID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequest{}
		var fernTestValuePracticeID string

		// Act
		obj.SetPracticeID(fernTestValuePracticeID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPatientID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequest{}
		var fernTestValuePatientID string

		// Act
		obj.SetPatientID(fernTestValuePatientID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAddress_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequest{}
		var fernTestValueAddress *CreatePatientAddressRequestAddress

		// Act
		obj.SetAddress(fernTestValueAddress)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLabel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequest{}
		var fernTestValueLabel *string

		// Act
		obj.SetLabel(fernTestValueLabel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPreferredShipping_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequest{}
		var fernTestValuePreferredShipping *bool

		// Act
		obj.SetPreferredShipping(fernTestValuePreferredShipping)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRecipientName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequest{}
		var fernTestValueRecipientName *string

		// Act
		obj.SetRecipientName(fernTestValueRecipientName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListAddressesRequest(t *testing.T) {
	t.Run("SetAffinityActorID", func(t *testing.T) {
		obj := &ListAddressesRequest{}
		var fernTestValueAffinityActorID *string
		obj.SetAffinityActorID(fernTestValueAffinityActorID)
		assert.Equal(t, fernTestValueAffinityActorID, obj.AffinityActorID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAffinityActorType", func(t *testing.T) {
		obj := &ListAddressesRequest{}
		var fernTestValueAffinityActorType *string
		obj.SetAffinityActorType(fernTestValueAffinityActorType)
		assert.Equal(t, fernTestValueAffinityActorType, obj.AffinityActorType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPracticeID", func(t *testing.T) {
		obj := &ListAddressesRequest{}
		var fernTestValuePracticeID string
		obj.SetPracticeID(fernTestValuePracticeID)
		assert.Equal(t, fernTestValuePracticeID, obj.PracticeID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPatientID", func(t *testing.T) {
		obj := &ListAddressesRequest{}
		var fernTestValuePatientID string
		obj.SetPatientID(fernTestValuePatientID)
		assert.Equal(t, fernTestValuePatientID, obj.PatientID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &ListAddressesRequest{}
		var fernTestValueStatus *ListAddressesRequestStatus
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStartingAfter", func(t *testing.T) {
		obj := &ListAddressesRequest{}
		var fernTestValueStartingAfter *string
		obj.SetStartingAfter(fernTestValueStartingAfter)
		assert.Equal(t, fernTestValueStartingAfter, obj.StartingAfter)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndingBefore", func(t *testing.T) {
		obj := &ListAddressesRequest{}
		var fernTestValueEndingBefore *string
		obj.SetEndingBefore(fernTestValueEndingBefore)
		assert.Equal(t, fernTestValueEndingBefore, obj.EndingBefore)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLimit", func(t *testing.T) {
		obj := &ListAddressesRequest{}
		var fernTestValueLimit *int
		obj.SetLimit(fernTestValueLimit)
		assert.Equal(t, fernTestValueLimit, obj.Limit)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListAddressesRequest(t *testing.T) {
	t.Run("SetAffinityActorID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListAddressesRequest{}
		var fernTestValueAffinityActorID *string

		// Act
		obj.SetAffinityActorID(fernTestValueAffinityActorID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAffinityActorType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListAddressesRequest{}
		var fernTestValueAffinityActorType *string

		// Act
		obj.SetAffinityActorType(fernTestValueAffinityActorType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPracticeID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListAddressesRequest{}
		var fernTestValuePracticeID string

		// Act
		obj.SetPracticeID(fernTestValuePracticeID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPatientID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListAddressesRequest{}
		var fernTestValuePatientID string

		// Act
		obj.SetPatientID(fernTestValuePatientID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListAddressesRequest{}
		var fernTestValueStatus *ListAddressesRequestStatus

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStartingAfter_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListAddressesRequest{}
		var fernTestValueStartingAfter *string

		// Act
		obj.SetStartingAfter(fernTestValueStartingAfter)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndingBefore_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListAddressesRequest{}
		var fernTestValueEndingBefore *string

		// Act
		obj.SetEndingBefore(fernTestValueEndingBefore)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListAddressesRequest{}
		var fernTestValueLimit *int

		// Act
		obj.SetLimit(fernTestValueLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSetDefaultAddressesRequest(t *testing.T) {
	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &SetDefaultAddressesRequest{}
		var fernTestValueIdempotencyKey *string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAffinityActorID", func(t *testing.T) {
		obj := &SetDefaultAddressesRequest{}
		var fernTestValueAffinityActorID *string
		obj.SetAffinityActorID(fernTestValueAffinityActorID)
		assert.Equal(t, fernTestValueAffinityActorID, obj.AffinityActorID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAffinityActorType", func(t *testing.T) {
		obj := &SetDefaultAddressesRequest{}
		var fernTestValueAffinityActorType *string
		obj.SetAffinityActorType(fernTestValueAffinityActorType)
		assert.Equal(t, fernTestValueAffinityActorType, obj.AffinityActorType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPracticeID", func(t *testing.T) {
		obj := &SetDefaultAddressesRequest{}
		var fernTestValuePracticeID string
		obj.SetPracticeID(fernTestValuePracticeID)
		assert.Equal(t, fernTestValuePracticeID, obj.PracticeID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPatientID", func(t *testing.T) {
		obj := &SetDefaultAddressesRequest{}
		var fernTestValuePatientID string
		obj.SetPatientID(fernTestValuePatientID)
		assert.Equal(t, fernTestValuePatientID, obj.PatientID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAddressID", func(t *testing.T) {
		obj := &SetDefaultAddressesRequest{}
		var fernTestValueAddressID string
		obj.SetAddressID(fernTestValueAddressID)
		assert.Equal(t, fernTestValueAddressID, obj.AddressID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSetDefaultAddressesRequest(t *testing.T) {
	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetDefaultAddressesRequest{}
		var fernTestValueIdempotencyKey *string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAffinityActorID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetDefaultAddressesRequest{}
		var fernTestValueAffinityActorID *string

		// Act
		obj.SetAffinityActorID(fernTestValueAffinityActorID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAffinityActorType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetDefaultAddressesRequest{}
		var fernTestValueAffinityActorType *string

		// Act
		obj.SetAffinityActorType(fernTestValueAffinityActorType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPracticeID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetDefaultAddressesRequest{}
		var fernTestValuePracticeID string

		// Act
		obj.SetPracticeID(fernTestValuePracticeID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPatientID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetDefaultAddressesRequest{}
		var fernTestValuePatientID string

		// Act
		obj.SetPatientID(fernTestValuePatientID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAddressID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetDefaultAddressesRequest{}
		var fernTestValueAddressID string

		// Act
		obj.SetAddressID(fernTestValueAddressID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreatePatientAddressRequestAddress(t *testing.T) {
	t.Run("SetCity", func(t *testing.T) {
		obj := &CreatePatientAddressRequestAddress{}
		var fernTestValueCity string
		obj.SetCity(fernTestValueCity)
		assert.Equal(t, fernTestValueCity, obj.City)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCountry", func(t *testing.T) {
		obj := &CreatePatientAddressRequestAddress{}
		var fernTestValueCountry *CreatePatientAddressRequestAddressCountry
		obj.SetCountry(fernTestValueCountry)
		assert.Equal(t, fernTestValueCountry, obj.Country)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLine1", func(t *testing.T) {
		obj := &CreatePatientAddressRequestAddress{}
		var fernTestValueLine1 string
		obj.SetLine1(fernTestValueLine1)
		assert.Equal(t, fernTestValueLine1, obj.Line1)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLine2", func(t *testing.T) {
		obj := &CreatePatientAddressRequestAddress{}
		var fernTestValueLine2 *string
		obj.SetLine2(fernTestValueLine2)
		assert.Equal(t, fernTestValueLine2, obj.Line2)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPostalCode", func(t *testing.T) {
		obj := &CreatePatientAddressRequestAddress{}
		var fernTestValuePostalCode string
		obj.SetPostalCode(fernTestValuePostalCode)
		assert.Equal(t, fernTestValuePostalCode, obj.PostalCode)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetState", func(t *testing.T) {
		obj := &CreatePatientAddressRequestAddress{}
		var fernTestValueState string
		obj.SetState(fernTestValueState)
		assert.Equal(t, fernTestValueState, obj.State)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCreatePatientAddressRequestAddress(t *testing.T) {
	t.Run("GetCity", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}
		var expected string
		obj.City = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCity(), "getter should return the property value")
	})

	t.Run("GetCity_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreatePatientAddressRequestAddress
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCity() // Should return zero value
	})

	t.Run("GetCountry", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}
		var expected *CreatePatientAddressRequestAddressCountry
		obj.Country = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCountry(), "getter should return the property value")
	})

	t.Run("GetCountry_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}
		obj.Country = nil

		// Act & Assert
		assert.Nil(t, obj.GetCountry(), "getter should return nil when property is nil")
	})

	t.Run("GetCountry_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreatePatientAddressRequestAddress
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCountry() // Should return zero value
	})

	t.Run("GetLine1", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}
		var expected string
		obj.Line1 = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLine1(), "getter should return the property value")
	})

	t.Run("GetLine1_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreatePatientAddressRequestAddress
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLine1() // Should return zero value
	})

	t.Run("GetLine2", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}
		var expected *string
		obj.Line2 = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLine2(), "getter should return the property value")
	})

	t.Run("GetLine2_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}
		obj.Line2 = nil

		// Act & Assert
		assert.Nil(t, obj.GetLine2(), "getter should return nil when property is nil")
	})

	t.Run("GetLine2_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreatePatientAddressRequestAddress
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLine2() // Should return zero value
	})

	t.Run("GetPostalCode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}
		var expected string
		obj.PostalCode = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPostalCode(), "getter should return the property value")
	})

	t.Run("GetPostalCode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreatePatientAddressRequestAddress
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPostalCode() // Should return zero value
	})

	t.Run("GetState", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}
		var expected string
		obj.State = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetState(), "getter should return the property value")
	})

	t.Run("GetState_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreatePatientAddressRequestAddress
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetState() // Should return zero value
	})

}

func TestSettersMarkExplicitCreatePatientAddressRequestAddress(t *testing.T) {
	t.Run("SetCity_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}
		var fernTestValueCity string

		// Act
		obj.SetCity(fernTestValueCity)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCountry_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}
		var fernTestValueCountry *CreatePatientAddressRequestAddressCountry

		// Act
		obj.SetCountry(fernTestValueCountry)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLine1_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}
		var fernTestValueLine1 string

		// Act
		obj.SetLine1(fernTestValueLine1)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLine2_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}
		var fernTestValueLine2 *string

		// Act
		obj.SetLine2(fernTestValueLine2)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPostalCode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}
		var fernTestValuePostalCode string

		// Act
		obj.SetPostalCode(fernTestValuePostalCode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetState_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}
		var fernTestValueState string

		// Act
		obj.SetState(fernTestValueState)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpdatePatientAddressRequestAddress(t *testing.T) {
	t.Run("SetCity", func(t *testing.T) {
		obj := &UpdatePatientAddressRequestAddress{}
		var fernTestValueCity string
		obj.SetCity(fernTestValueCity)
		assert.Equal(t, fernTestValueCity, obj.City)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCountry", func(t *testing.T) {
		obj := &UpdatePatientAddressRequestAddress{}
		var fernTestValueCountry *UpdatePatientAddressRequestAddressCountry
		obj.SetCountry(fernTestValueCountry)
		assert.Equal(t, fernTestValueCountry, obj.Country)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLine1", func(t *testing.T) {
		obj := &UpdatePatientAddressRequestAddress{}
		var fernTestValueLine1 string
		obj.SetLine1(fernTestValueLine1)
		assert.Equal(t, fernTestValueLine1, obj.Line1)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLine2", func(t *testing.T) {
		obj := &UpdatePatientAddressRequestAddress{}
		var fernTestValueLine2 *string
		obj.SetLine2(fernTestValueLine2)
		assert.Equal(t, fernTestValueLine2, obj.Line2)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPostalCode", func(t *testing.T) {
		obj := &UpdatePatientAddressRequestAddress{}
		var fernTestValuePostalCode string
		obj.SetPostalCode(fernTestValuePostalCode)
		assert.Equal(t, fernTestValuePostalCode, obj.PostalCode)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetState", func(t *testing.T) {
		obj := &UpdatePatientAddressRequestAddress{}
		var fernTestValueState string
		obj.SetState(fernTestValueState)
		assert.Equal(t, fernTestValueState, obj.State)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersUpdatePatientAddressRequestAddress(t *testing.T) {
	t.Run("GetCity", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}
		var expected string
		obj.City = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCity(), "getter should return the property value")
	})

	t.Run("GetCity_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdatePatientAddressRequestAddress
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCity() // Should return zero value
	})

	t.Run("GetCountry", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}
		var expected *UpdatePatientAddressRequestAddressCountry
		obj.Country = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCountry(), "getter should return the property value")
	})

	t.Run("GetCountry_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}
		obj.Country = nil

		// Act & Assert
		assert.Nil(t, obj.GetCountry(), "getter should return nil when property is nil")
	})

	t.Run("GetCountry_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdatePatientAddressRequestAddress
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCountry() // Should return zero value
	})

	t.Run("GetLine1", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}
		var expected string
		obj.Line1 = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLine1(), "getter should return the property value")
	})

	t.Run("GetLine1_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdatePatientAddressRequestAddress
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLine1() // Should return zero value
	})

	t.Run("GetLine2", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}
		var expected *string
		obj.Line2 = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLine2(), "getter should return the property value")
	})

	t.Run("GetLine2_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}
		obj.Line2 = nil

		// Act & Assert
		assert.Nil(t, obj.GetLine2(), "getter should return nil when property is nil")
	})

	t.Run("GetLine2_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdatePatientAddressRequestAddress
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLine2() // Should return zero value
	})

	t.Run("GetPostalCode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}
		var expected string
		obj.PostalCode = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPostalCode(), "getter should return the property value")
	})

	t.Run("GetPostalCode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdatePatientAddressRequestAddress
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPostalCode() // Should return zero value
	})

	t.Run("GetState", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}
		var expected string
		obj.State = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetState(), "getter should return the property value")
	})

	t.Run("GetState_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdatePatientAddressRequestAddress
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetState() // Should return zero value
	})

}

func TestSettersMarkExplicitUpdatePatientAddressRequestAddress(t *testing.T) {
	t.Run("SetCity_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}
		var fernTestValueCity string

		// Act
		obj.SetCity(fernTestValueCity)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCountry_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}
		var fernTestValueCountry *UpdatePatientAddressRequestAddressCountry

		// Act
		obj.SetCountry(fernTestValueCountry)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLine1_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}
		var fernTestValueLine1 string

		// Act
		obj.SetLine1(fernTestValueLine1)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLine2_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}
		var fernTestValueLine2 *string

		// Act
		obj.SetLine2(fernTestValueLine2)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPostalCode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}
		var fernTestValuePostalCode string

		// Act
		obj.SetPostalCode(fernTestValuePostalCode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetState_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}
		var fernTestValueState string

		// Act
		obj.SetState(fernTestValueState)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpdatePatientAddressRequest(t *testing.T) {
	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &UpdatePatientAddressRequest{}
		var fernTestValueIdempotencyKey *string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAffinityActorID", func(t *testing.T) {
		obj := &UpdatePatientAddressRequest{}
		var fernTestValueAffinityActorID *string
		obj.SetAffinityActorID(fernTestValueAffinityActorID)
		assert.Equal(t, fernTestValueAffinityActorID, obj.AffinityActorID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAffinityActorType", func(t *testing.T) {
		obj := &UpdatePatientAddressRequest{}
		var fernTestValueAffinityActorType *string
		obj.SetAffinityActorType(fernTestValueAffinityActorType)
		assert.Equal(t, fernTestValueAffinityActorType, obj.AffinityActorType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPracticeID", func(t *testing.T) {
		obj := &UpdatePatientAddressRequest{}
		var fernTestValuePracticeID string
		obj.SetPracticeID(fernTestValuePracticeID)
		assert.Equal(t, fernTestValuePracticeID, obj.PracticeID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPatientID", func(t *testing.T) {
		obj := &UpdatePatientAddressRequest{}
		var fernTestValuePatientID string
		obj.SetPatientID(fernTestValuePatientID)
		assert.Equal(t, fernTestValuePatientID, obj.PatientID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAddressID", func(t *testing.T) {
		obj := &UpdatePatientAddressRequest{}
		var fernTestValueAddressID string
		obj.SetAddressID(fernTestValueAddressID)
		assert.Equal(t, fernTestValueAddressID, obj.AddressID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAddress", func(t *testing.T) {
		obj := &UpdatePatientAddressRequest{}
		var fernTestValueAddress *UpdatePatientAddressRequestAddress
		obj.SetAddress(fernTestValueAddress)
		assert.Equal(t, fernTestValueAddress, obj.Address)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLabel", func(t *testing.T) {
		obj := &UpdatePatientAddressRequest{}
		var fernTestValueLabel *string
		obj.SetLabel(fernTestValueLabel)
		assert.Equal(t, fernTestValueLabel, obj.Label)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRecipientName", func(t *testing.T) {
		obj := &UpdatePatientAddressRequest{}
		var fernTestValueRecipientName *string
		obj.SetRecipientName(fernTestValueRecipientName)
		assert.Equal(t, fernTestValueRecipientName, obj.RecipientName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPreferredShipping", func(t *testing.T) {
		obj := &UpdatePatientAddressRequest{}
		var fernTestValuePreferredShipping *bool
		obj.SetPreferredShipping(fernTestValuePreferredShipping)
		assert.Equal(t, fernTestValuePreferredShipping, obj.PreferredShipping)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitUpdatePatientAddressRequest(t *testing.T) {
	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequest{}
		var fernTestValueIdempotencyKey *string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAffinityActorID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequest{}
		var fernTestValueAffinityActorID *string

		// Act
		obj.SetAffinityActorID(fernTestValueAffinityActorID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAffinityActorType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequest{}
		var fernTestValueAffinityActorType *string

		// Act
		obj.SetAffinityActorType(fernTestValueAffinityActorType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPracticeID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequest{}
		var fernTestValuePracticeID string

		// Act
		obj.SetPracticeID(fernTestValuePracticeID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPatientID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequest{}
		var fernTestValuePatientID string

		// Act
		obj.SetPatientID(fernTestValuePatientID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAddressID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequest{}
		var fernTestValueAddressID string

		// Act
		obj.SetAddressID(fernTestValueAddressID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAddress_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequest{}
		var fernTestValueAddress *UpdatePatientAddressRequestAddress

		// Act
		obj.SetAddress(fernTestValueAddress)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLabel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequest{}
		var fernTestValueLabel *string

		// Act
		obj.SetLabel(fernTestValueLabel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRecipientName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequest{}
		var fernTestValueRecipientName *string

		// Act
		obj.SetRecipientName(fernTestValueRecipientName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPreferredShipping_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequest{}
		var fernTestValuePreferredShipping *bool

		// Act
		obj.SetPreferredShipping(fernTestValuePreferredShipping)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingCreatePatientAddressRequestAddress(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePatientAddressRequestAddress{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CreatePatientAddressRequestAddress
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CreatePatientAddressRequestAddress
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CreatePatientAddressRequestAddress
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingUpdatePatientAddressRequestAddress(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdatePatientAddressRequestAddress{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled UpdatePatientAddressRequestAddress
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj UpdatePatientAddressRequestAddress
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj UpdatePatientAddressRequestAddress
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringCreatePatientAddressRequestAddress(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CreatePatientAddressRequestAddress{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreatePatientAddressRequestAddress
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringUpdatePatientAddressRequestAddress(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &UpdatePatientAddressRequestAddress{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdatePatientAddressRequestAddress
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumCreatePatientAddressRequestAddressCountry(t *testing.T) {
	t.Run("NewFromString_US", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePatientAddressRequestAddressCountryFromString("US")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePatientAddressRequestAddressCountry("US"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewCreatePatientAddressRequestAddressCountryFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewCreatePatientAddressRequestAddressCountryFromString("US")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumListAddressesRequestStatus(t *testing.T) {
	t.Run("NewFromString_active", func(t *testing.T) {
		t.Parallel()
		val, err := NewListAddressesRequestStatusFromString("active")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListAddressesRequestStatus("active"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_archived", func(t *testing.T) {
		t.Parallel()
		val, err := NewListAddressesRequestStatusFromString("archived")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListAddressesRequestStatus("archived"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_all", func(t *testing.T) {
		t.Parallel()
		val, err := NewListAddressesRequestStatusFromString("all")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListAddressesRequestStatus("all"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewListAddressesRequestStatusFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewListAddressesRequestStatusFromString("active")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumUpdatePatientAddressRequestAddressCountry(t *testing.T) {
	t.Run("NewFromString_US", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdatePatientAddressRequestAddressCountryFromString("US")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdatePatientAddressRequestAddressCountry("US"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewUpdatePatientAddressRequestAddressCountryFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewUpdatePatientAddressRequestAddressCountryFromString("US")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesCreatePatientAddressRequestAddress(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CreatePatientAddressRequestAddress{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreatePatientAddressRequestAddress
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesUpdatePatientAddressRequestAddress(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &UpdatePatientAddressRequestAddress{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdatePatientAddressRequestAddress
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
