// Code generated by Fern. DO NOT EDIT.

package patients

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/affinity-health/affinity-go/internal"
	big "math/big"
)

var (
	getAllergiesRequestFieldAffinityActorID   = big.NewInt(1 << 0)
	getAllergiesRequestFieldAffinityActorType = big.NewInt(1 << 1)
	getAllergiesRequestFieldPracticeID        = big.NewInt(1 << 2)
	getAllergiesRequestFieldPatientID         = big.NewInt(1 << 3)
)

type GetAllergiesRequest struct {
	// Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.
	AffinityActorID *string `json:"-" url:"-"`
	// Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.
	AffinityActorType *string `json:"-" url:"-"`
	PracticeID        string  `json:"-" url:"-"`
	PatientID         string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetAllergiesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAffinityActorID sets the AffinityActorID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAllergiesRequest) SetAffinityActorID(affinityActorID *string) {
	g.AffinityActorID = affinityActorID
	g.require(getAllergiesRequestFieldAffinityActorID)
}

// SetAffinityActorType sets the AffinityActorType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAllergiesRequest) SetAffinityActorType(affinityActorType *string) {
	g.AffinityActorType = affinityActorType
	g.require(getAllergiesRequestFieldAffinityActorType)
}

// SetPracticeID sets the PracticeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAllergiesRequest) SetPracticeID(practiceID string) {
	g.PracticeID = practiceID
	g.require(getAllergiesRequestFieldPracticeID)
}

// SetPatientID sets the PatientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAllergiesRequest) SetPatientID(patientID string) {
	g.PatientID = patientID
	g.require(getAllergiesRequestFieldPatientID)
}

var (
	replacePatientAllergiesRequestFieldIdempotencyKey    = big.NewInt(1 << 0)
	replacePatientAllergiesRequestFieldAffinityActorID   = big.NewInt(1 << 1)
	replacePatientAllergiesRequestFieldAffinityActorType = big.NewInt(1 << 2)
	replacePatientAllergiesRequestFieldPracticeID        = big.NewInt(1 << 3)
	replacePatientAllergiesRequestFieldPatientID         = big.NewInt(1 << 4)
	replacePatientAllergiesRequestFieldAllergies         = big.NewInt(1 << 5)
	replacePatientAllergiesRequestFieldReviewStatus      = big.NewInt(1 << 6)
)

type ReplacePatientAllergiesRequest struct {
	IdempotencyKey string `json:"-" url:"-"`
	// Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.
	AffinityActorID *string `json:"-" url:"-"`
	// Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.
	AffinityActorType *string                                        `json:"-" url:"-"`
	PracticeID        string                                         `json:"-" url:"-"`
	PatientID         string                                         `json:"-" url:"-"`
	Allergies         []*ReplacePatientAllergiesRequestAllergiesItem `json:"allergies" url:"-"`
	ReviewStatus      ReplacePatientAllergiesRequestReviewStatus     `json:"reviewStatus" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReplacePatientAllergiesRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequest) SetIdempotencyKey(idempotencyKey string) {
	r.IdempotencyKey = idempotencyKey
	r.require(replacePatientAllergiesRequestFieldIdempotencyKey)
}

// SetAffinityActorID sets the AffinityActorID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequest) SetAffinityActorID(affinityActorID *string) {
	r.AffinityActorID = affinityActorID
	r.require(replacePatientAllergiesRequestFieldAffinityActorID)
}

// SetAffinityActorType sets the AffinityActorType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequest) SetAffinityActorType(affinityActorType *string) {
	r.AffinityActorType = affinityActorType
	r.require(replacePatientAllergiesRequestFieldAffinityActorType)
}

// SetPracticeID sets the PracticeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequest) SetPracticeID(practiceID string) {
	r.PracticeID = practiceID
	r.require(replacePatientAllergiesRequestFieldPracticeID)
}

// SetPatientID sets the PatientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequest) SetPatientID(patientID string) {
	r.PatientID = patientID
	r.require(replacePatientAllergiesRequestFieldPatientID)
}

// SetAllergies sets the Allergies field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequest) SetAllergies(allergies []*ReplacePatientAllergiesRequestAllergiesItem) {
	r.Allergies = allergies
	r.require(replacePatientAllergiesRequestFieldAllergies)
}

// SetReviewStatus sets the ReviewStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequest) SetReviewStatus(reviewStatus ReplacePatientAllergiesRequestReviewStatus) {
	r.ReviewStatus = reviewStatus
	r.require(replacePatientAllergiesRequestFieldReviewStatus)
}

func (r *ReplacePatientAllergiesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ReplacePatientAllergiesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = ReplacePatientAllergiesRequest(body)
	return nil
}

func (r *ReplacePatientAllergiesRequest) MarshalJSON() ([]byte, error) {
	type embed ReplacePatientAllergiesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	replacePatientAllergiesRequestAllergiesItemFieldCategory           = big.NewInt(1 << 0)
	replacePatientAllergiesRequestAllergiesItemFieldCode               = big.NewInt(1 << 1)
	replacePatientAllergiesRequestAllergiesItemFieldCodeSystem         = big.NewInt(1 << 2)
	replacePatientAllergiesRequestAllergiesItemFieldReactions          = big.NewInt(1 << 3)
	replacePatientAllergiesRequestAllergiesItemFieldSeverity           = big.NewInt(1 << 4)
	replacePatientAllergiesRequestAllergiesItemFieldSource             = big.NewInt(1 << 5)
	replacePatientAllergiesRequestAllergiesItemFieldSubstance          = big.NewInt(1 << 6)
	replacePatientAllergiesRequestAllergiesItemFieldType               = big.NewInt(1 << 7)
	replacePatientAllergiesRequestAllergiesItemFieldVerificationStatus = big.NewInt(1 << 8)
)

type ReplacePatientAllergiesRequestAllergiesItem struct {
	Category           ReplacePatientAllergiesRequestAllergiesItemCategory           `json:"category" url:"category"`
	Code               *string                                                       `json:"code,omitempty" url:"code,omitempty"`
	CodeSystem         *ReplacePatientAllergiesRequestAllergiesItemCodeSystem        `json:"codeSystem,omitempty" url:"codeSystem,omitempty"`
	Reactions          []*ReplacePatientAllergiesRequestAllergiesItemReactionsItem   `json:"reactions" url:"reactions"`
	Severity           *ReplacePatientAllergiesRequestAllergiesItemSeverity          `json:"severity,omitempty" url:"severity,omitempty"`
	Source             ReplacePatientAllergiesRequestAllergiesItemSource             `json:"source" url:"source"`
	Substance          string                                                        `json:"substance" url:"substance"`
	Type               *ReplacePatientAllergiesRequestAllergiesItemType              `json:"type,omitempty" url:"type,omitempty"`
	VerificationStatus ReplacePatientAllergiesRequestAllergiesItemVerificationStatus `json:"verificationStatus" url:"verificationStatus"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReplacePatientAllergiesRequestAllergiesItem) GetCategory() ReplacePatientAllergiesRequestAllergiesItemCategory {
	if r == nil {
		return ""
	}
	return r.Category
}

func (r *ReplacePatientAllergiesRequestAllergiesItem) GetCode() *string {
	if r == nil {
		return nil
	}
	return r.Code
}

func (r *ReplacePatientAllergiesRequestAllergiesItem) GetCodeSystem() *ReplacePatientAllergiesRequestAllergiesItemCodeSystem {
	if r == nil {
		return nil
	}
	return r.CodeSystem
}

func (r *ReplacePatientAllergiesRequestAllergiesItem) GetReactions() []*ReplacePatientAllergiesRequestAllergiesItemReactionsItem {
	if r == nil {
		return nil
	}
	return r.Reactions
}

func (r *ReplacePatientAllergiesRequestAllergiesItem) GetSeverity() *ReplacePatientAllergiesRequestAllergiesItemSeverity {
	if r == nil {
		return nil
	}
	return r.Severity
}

func (r *ReplacePatientAllergiesRequestAllergiesItem) GetSource() ReplacePatientAllergiesRequestAllergiesItemSource {
	if r == nil {
		return ""
	}
	return r.Source
}

func (r *ReplacePatientAllergiesRequestAllergiesItem) GetSubstance() string {
	if r == nil {
		return ""
	}
	return r.Substance
}

func (r *ReplacePatientAllergiesRequestAllergiesItem) GetType() *ReplacePatientAllergiesRequestAllergiesItemType {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *ReplacePatientAllergiesRequestAllergiesItem) GetVerificationStatus() ReplacePatientAllergiesRequestAllergiesItemVerificationStatus {
	if r == nil {
		return ""
	}
	return r.VerificationStatus
}

func (r *ReplacePatientAllergiesRequestAllergiesItem) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReplacePatientAllergiesRequestAllergiesItem) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetCategory sets the Category field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequestAllergiesItem) SetCategory(category ReplacePatientAllergiesRequestAllergiesItemCategory) {
	r.Category = category
	r.require(replacePatientAllergiesRequestAllergiesItemFieldCategory)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequestAllergiesItem) SetCode(code *string) {
	r.Code = code
	r.require(replacePatientAllergiesRequestAllergiesItemFieldCode)
}

// SetCodeSystem sets the CodeSystem field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequestAllergiesItem) SetCodeSystem(codeSystem *ReplacePatientAllergiesRequestAllergiesItemCodeSystem) {
	r.CodeSystem = codeSystem
	r.require(replacePatientAllergiesRequestAllergiesItemFieldCodeSystem)
}

// SetReactions sets the Reactions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequestAllergiesItem) SetReactions(reactions []*ReplacePatientAllergiesRequestAllergiesItemReactionsItem) {
	r.Reactions = reactions
	r.require(replacePatientAllergiesRequestAllergiesItemFieldReactions)
}

// SetSeverity sets the Severity field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequestAllergiesItem) SetSeverity(severity *ReplacePatientAllergiesRequestAllergiesItemSeverity) {
	r.Severity = severity
	r.require(replacePatientAllergiesRequestAllergiesItemFieldSeverity)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequestAllergiesItem) SetSource(source ReplacePatientAllergiesRequestAllergiesItemSource) {
	r.Source = source
	r.require(replacePatientAllergiesRequestAllergiesItemFieldSource)
}

// SetSubstance sets the Substance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequestAllergiesItem) SetSubstance(substance string) {
	r.Substance = substance
	r.require(replacePatientAllergiesRequestAllergiesItemFieldSubstance)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequestAllergiesItem) SetType(type_ *ReplacePatientAllergiesRequestAllergiesItemType) {
	r.Type = type_
	r.require(replacePatientAllergiesRequestAllergiesItemFieldType)
}

// SetVerificationStatus sets the VerificationStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequestAllergiesItem) SetVerificationStatus(verificationStatus ReplacePatientAllergiesRequestAllergiesItemVerificationStatus) {
	r.VerificationStatus = verificationStatus
	r.require(replacePatientAllergiesRequestAllergiesItemFieldVerificationStatus)
}

func (r *ReplacePatientAllergiesRequestAllergiesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ReplacePatientAllergiesRequestAllergiesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReplacePatientAllergiesRequestAllergiesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReplacePatientAllergiesRequestAllergiesItem) MarshalJSON() ([]byte, error) {
	type embed ReplacePatientAllergiesRequestAllergiesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReplacePatientAllergiesRequestAllergiesItem) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type ReplacePatientAllergiesRequestAllergiesItemCategory string

const (
	ReplacePatientAllergiesRequestAllergiesItemCategoryDrug          ReplacePatientAllergiesRequestAllergiesItemCategory = "drug"
	ReplacePatientAllergiesRequestAllergiesItemCategoryFood          ReplacePatientAllergiesRequestAllergiesItemCategory = "food"
	ReplacePatientAllergiesRequestAllergiesItemCategoryInsect        ReplacePatientAllergiesRequestAllergiesItemCategory = "insect"
	ReplacePatientAllergiesRequestAllergiesItemCategoryLatex         ReplacePatientAllergiesRequestAllergiesItemCategory = "latex"
	ReplacePatientAllergiesRequestAllergiesItemCategoryMold          ReplacePatientAllergiesRequestAllergiesItemCategory = "mold"
	ReplacePatientAllergiesRequestAllergiesItemCategoryPet           ReplacePatientAllergiesRequestAllergiesItemCategory = "pet"
	ReplacePatientAllergiesRequestAllergiesItemCategoryPollen        ReplacePatientAllergiesRequestAllergiesItemCategory = "pollen"
	ReplacePatientAllergiesRequestAllergiesItemCategoryEnvironmental ReplacePatientAllergiesRequestAllergiesItemCategory = "environmental"
	ReplacePatientAllergiesRequestAllergiesItemCategoryBiologic      ReplacePatientAllergiesRequestAllergiesItemCategory = "biologic"
	ReplacePatientAllergiesRequestAllergiesItemCategoryOther         ReplacePatientAllergiesRequestAllergiesItemCategory = "other"
)

func NewReplacePatientAllergiesRequestAllergiesItemCategoryFromString(s string) (ReplacePatientAllergiesRequestAllergiesItemCategory, error) {
	switch s {
	case "drug":
		return ReplacePatientAllergiesRequestAllergiesItemCategoryDrug, nil
	case "food":
		return ReplacePatientAllergiesRequestAllergiesItemCategoryFood, nil
	case "insect":
		return ReplacePatientAllergiesRequestAllergiesItemCategoryInsect, nil
	case "latex":
		return ReplacePatientAllergiesRequestAllergiesItemCategoryLatex, nil
	case "mold":
		return ReplacePatientAllergiesRequestAllergiesItemCategoryMold, nil
	case "pet":
		return ReplacePatientAllergiesRequestAllergiesItemCategoryPet, nil
	case "pollen":
		return ReplacePatientAllergiesRequestAllergiesItemCategoryPollen, nil
	case "environmental":
		return ReplacePatientAllergiesRequestAllergiesItemCategoryEnvironmental, nil
	case "biologic":
		return ReplacePatientAllergiesRequestAllergiesItemCategoryBiologic, nil
	case "other":
		return ReplacePatientAllergiesRequestAllergiesItemCategoryOther, nil
	}
	var t ReplacePatientAllergiesRequestAllergiesItemCategory
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r ReplacePatientAllergiesRequestAllergiesItemCategory) Ptr() *ReplacePatientAllergiesRequestAllergiesItemCategory {
	return &r
}

type ReplacePatientAllergiesRequestAllergiesItemCodeSystem string

const (
	ReplacePatientAllergiesRequestAllergiesItemCodeSystemRxnorm   ReplacePatientAllergiesRequestAllergiesItemCodeSystem = "rxnorm"
	ReplacePatientAllergiesRequestAllergiesItemCodeSystemSnomedCt ReplacePatientAllergiesRequestAllergiesItemCodeSystem = "snomed-ct"
)

func NewReplacePatientAllergiesRequestAllergiesItemCodeSystemFromString(s string) (ReplacePatientAllergiesRequestAllergiesItemCodeSystem, error) {
	switch s {
	case "rxnorm":
		return ReplacePatientAllergiesRequestAllergiesItemCodeSystemRxnorm, nil
	case "snomed-ct":
		return ReplacePatientAllergiesRequestAllergiesItemCodeSystemSnomedCt, nil
	}
	var t ReplacePatientAllergiesRequestAllergiesItemCodeSystem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r ReplacePatientAllergiesRequestAllergiesItemCodeSystem) Ptr() *ReplacePatientAllergiesRequestAllergiesItemCodeSystem {
	return &r
}

var (
	replacePatientAllergiesRequestAllergiesItemReactionsItemFieldCode       = big.NewInt(1 << 0)
	replacePatientAllergiesRequestAllergiesItemReactionsItemFieldCodeSystem = big.NewInt(1 << 1)
	replacePatientAllergiesRequestAllergiesItemReactionsItemFieldDisplay    = big.NewInt(1 << 2)
)

type ReplacePatientAllergiesRequestAllergiesItemReactionsItem struct {
	Code       *string                                                             `json:"code,omitempty" url:"code,omitempty"`
	CodeSystem *ReplacePatientAllergiesRequestAllergiesItemReactionsItemCodeSystem `json:"codeSystem,omitempty" url:"codeSystem,omitempty"`
	Display    string                                                              `json:"display" url:"display"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReplacePatientAllergiesRequestAllergiesItemReactionsItem) GetCode() *string {
	if r == nil {
		return nil
	}
	return r.Code
}

func (r *ReplacePatientAllergiesRequestAllergiesItemReactionsItem) GetCodeSystem() *ReplacePatientAllergiesRequestAllergiesItemReactionsItemCodeSystem {
	if r == nil {
		return nil
	}
	return r.CodeSystem
}

func (r *ReplacePatientAllergiesRequestAllergiesItemReactionsItem) GetDisplay() string {
	if r == nil {
		return ""
	}
	return r.Display
}

func (r *ReplacePatientAllergiesRequestAllergiesItemReactionsItem) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReplacePatientAllergiesRequestAllergiesItemReactionsItem) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequestAllergiesItemReactionsItem) SetCode(code *string) {
	r.Code = code
	r.require(replacePatientAllergiesRequestAllergiesItemReactionsItemFieldCode)
}

// SetCodeSystem sets the CodeSystem field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequestAllergiesItemReactionsItem) SetCodeSystem(codeSystem *ReplacePatientAllergiesRequestAllergiesItemReactionsItemCodeSystem) {
	r.CodeSystem = codeSystem
	r.require(replacePatientAllergiesRequestAllergiesItemReactionsItemFieldCodeSystem)
}

// SetDisplay sets the Display field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplacePatientAllergiesRequestAllergiesItemReactionsItem) SetDisplay(display string) {
	r.Display = display
	r.require(replacePatientAllergiesRequestAllergiesItemReactionsItemFieldDisplay)
}

func (r *ReplacePatientAllergiesRequestAllergiesItemReactionsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ReplacePatientAllergiesRequestAllergiesItemReactionsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReplacePatientAllergiesRequestAllergiesItemReactionsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReplacePatientAllergiesRequestAllergiesItemReactionsItem) MarshalJSON() ([]byte, error) {
	type embed ReplacePatientAllergiesRequestAllergiesItemReactionsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReplacePatientAllergiesRequestAllergiesItemReactionsItem) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type ReplacePatientAllergiesRequestAllergiesItemReactionsItemCodeSystem string

const (
	ReplacePatientAllergiesRequestAllergiesItemReactionsItemCodeSystemSnomedCt ReplacePatientAllergiesRequestAllergiesItemReactionsItemCodeSystem = "snomed-ct"
)

func NewReplacePatientAllergiesRequestAllergiesItemReactionsItemCodeSystemFromString(s string) (ReplacePatientAllergiesRequestAllergiesItemReactionsItemCodeSystem, error) {
	switch s {
	case "snomed-ct":
		return ReplacePatientAllergiesRequestAllergiesItemReactionsItemCodeSystemSnomedCt, nil
	}
	var t ReplacePatientAllergiesRequestAllergiesItemReactionsItemCodeSystem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r ReplacePatientAllergiesRequestAllergiesItemReactionsItemCodeSystem) Ptr() *ReplacePatientAllergiesRequestAllergiesItemReactionsItemCodeSystem {
	return &r
}

type ReplacePatientAllergiesRequestAllergiesItemSeverity string

const (
	ReplacePatientAllergiesRequestAllergiesItemSeverityMild     ReplacePatientAllergiesRequestAllergiesItemSeverity = "mild"
	ReplacePatientAllergiesRequestAllergiesItemSeverityModerate ReplacePatientAllergiesRequestAllergiesItemSeverity = "moderate"
	ReplacePatientAllergiesRequestAllergiesItemSeveritySevere   ReplacePatientAllergiesRequestAllergiesItemSeverity = "severe"
	ReplacePatientAllergiesRequestAllergiesItemSeverityUnknown  ReplacePatientAllergiesRequestAllergiesItemSeverity = "unknown"
)

func NewReplacePatientAllergiesRequestAllergiesItemSeverityFromString(s string) (ReplacePatientAllergiesRequestAllergiesItemSeverity, error) {
	switch s {
	case "mild":
		return ReplacePatientAllergiesRequestAllergiesItemSeverityMild, nil
	case "moderate":
		return ReplacePatientAllergiesRequestAllergiesItemSeverityModerate, nil
	case "severe":
		return ReplacePatientAllergiesRequestAllergiesItemSeveritySevere, nil
	case "unknown":
		return ReplacePatientAllergiesRequestAllergiesItemSeverityUnknown, nil
	}
	var t ReplacePatientAllergiesRequestAllergiesItemSeverity
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r ReplacePatientAllergiesRequestAllergiesItemSeverity) Ptr() *ReplacePatientAllergiesRequestAllergiesItemSeverity {
	return &r
}

type ReplacePatientAllergiesRequestAllergiesItemSource string

const (
	ReplacePatientAllergiesRequestAllergiesItemSourceDoctor               ReplacePatientAllergiesRequestAllergiesItemSource = "Doctor"
	ReplacePatientAllergiesRequestAllergiesItemSourcePatient              ReplacePatientAllergiesRequestAllergiesItemSource = "Patient"
	ReplacePatientAllergiesRequestAllergiesItemSourcePatientAgentGuardian ReplacePatientAllergiesRequestAllergiesItemSource = "Patient Agent/Guardian"
	ReplacePatientAllergiesRequestAllergiesItemSourcePharmacist           ReplacePatientAllergiesRequestAllergiesItemSource = "Pharmacist"
)

func NewReplacePatientAllergiesRequestAllergiesItemSourceFromString(s string) (ReplacePatientAllergiesRequestAllergiesItemSource, error) {
	switch s {
	case "Doctor":
		return ReplacePatientAllergiesRequestAllergiesItemSourceDoctor, nil
	case "Patient":
		return ReplacePatientAllergiesRequestAllergiesItemSourcePatient, nil
	case "Patient Agent/Guardian":
		return ReplacePatientAllergiesRequestAllergiesItemSourcePatientAgentGuardian, nil
	case "Pharmacist":
		return ReplacePatientAllergiesRequestAllergiesItemSourcePharmacist, nil
	}
	var t ReplacePatientAllergiesRequestAllergiesItemSource
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r ReplacePatientAllergiesRequestAllergiesItemSource) Ptr() *ReplacePatientAllergiesRequestAllergiesItemSource {
	return &r
}

type ReplacePatientAllergiesRequestAllergiesItemType string

const (
	ReplacePatientAllergiesRequestAllergiesItemTypeAllergy     ReplacePatientAllergiesRequestAllergiesItemType = "allergy"
	ReplacePatientAllergiesRequestAllergiesItemTypeIntolerance ReplacePatientAllergiesRequestAllergiesItemType = "intolerance"
)

func NewReplacePatientAllergiesRequestAllergiesItemTypeFromString(s string) (ReplacePatientAllergiesRequestAllergiesItemType, error) {
	switch s {
	case "allergy":
		return ReplacePatientAllergiesRequestAllergiesItemTypeAllergy, nil
	case "intolerance":
		return ReplacePatientAllergiesRequestAllergiesItemTypeIntolerance, nil
	}
	var t ReplacePatientAllergiesRequestAllergiesItemType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r ReplacePatientAllergiesRequestAllergiesItemType) Ptr() *ReplacePatientAllergiesRequestAllergiesItemType {
	return &r
}

type ReplacePatientAllergiesRequestAllergiesItemVerificationStatus string

const (
	ReplacePatientAllergiesRequestAllergiesItemVerificationStatusUnconfirmed ReplacePatientAllergiesRequestAllergiesItemVerificationStatus = "unconfirmed"
	ReplacePatientAllergiesRequestAllergiesItemVerificationStatusPresumed    ReplacePatientAllergiesRequestAllergiesItemVerificationStatus = "presumed"
	ReplacePatientAllergiesRequestAllergiesItemVerificationStatusConfirmed   ReplacePatientAllergiesRequestAllergiesItemVerificationStatus = "confirmed"
)

func NewReplacePatientAllergiesRequestAllergiesItemVerificationStatusFromString(s string) (ReplacePatientAllergiesRequestAllergiesItemVerificationStatus, error) {
	switch s {
	case "unconfirmed":
		return ReplacePatientAllergiesRequestAllergiesItemVerificationStatusUnconfirmed, nil
	case "presumed":
		return ReplacePatientAllergiesRequestAllergiesItemVerificationStatusPresumed, nil
	case "confirmed":
		return ReplacePatientAllergiesRequestAllergiesItemVerificationStatusConfirmed, nil
	}
	var t ReplacePatientAllergiesRequestAllergiesItemVerificationStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r ReplacePatientAllergiesRequestAllergiesItemVerificationStatus) Ptr() *ReplacePatientAllergiesRequestAllergiesItemVerificationStatus {
	return &r
}

type ReplacePatientAllergiesRequestReviewStatus string

const (
	ReplacePatientAllergiesRequestReviewStatusNotReviewed ReplacePatientAllergiesRequestReviewStatus = "not_reviewed"
	ReplacePatientAllergiesRequestReviewStatusNoKnown     ReplacePatientAllergiesRequestReviewStatus = "no_known"
	ReplacePatientAllergiesRequestReviewStatusRecorded    ReplacePatientAllergiesRequestReviewStatus = "recorded"
)

func NewReplacePatientAllergiesRequestReviewStatusFromString(s string) (ReplacePatientAllergiesRequestReviewStatus, error) {
	switch s {
	case "not_reviewed":
		return ReplacePatientAllergiesRequestReviewStatusNotReviewed, nil
	case "no_known":
		return ReplacePatientAllergiesRequestReviewStatusNoKnown, nil
	case "recorded":
		return ReplacePatientAllergiesRequestReviewStatusRecorded, nil
	}
	var t ReplacePatientAllergiesRequestReviewStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r ReplacePatientAllergiesRequestReviewStatus) Ptr() *ReplacePatientAllergiesRequestReviewStatus {
	return &r
}
