// Code generated by Fern. DO NOT EDIT.

package patients

import (
	context "context"
	http "net/http"

	affinity "github.com/affinity-health/affinity-go"
	core "github.com/affinity-health/affinity-go/core"
	internal "github.com/affinity-health/affinity-go/internal"
	option "github.com/affinity-health/affinity-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListPatientAddresses(
	ctx context.Context,
	request *affinity.ListPatientAddressesRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.ListPatientAddressesResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/patients/%v/addresses",
		request.PracticeID,
		request.PatientID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.AffinityActorID != nil {
		headers.Add("Affinity-Actor-Id", *request.AffinityActorID)
	}
	if request.AffinityActorType != nil {
		headers.Add("Affinity-Actor-Type", *request.AffinityActorType)
	}

	var response *affinity.ListPatientAddressesResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.ListPatientAddressesResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreatePatientAddress(
	ctx context.Context,
	request *affinity.CreatePatientAddressRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.CreatePatientAddressResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/patients/%v/addresses",
		request.PracticeID,
		request.PatientID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	if request.AffinityActorID != nil {
		headers.Add("Affinity-Actor-Id", *request.AffinityActorID)
	}
	if request.AffinityActorType != nil {
		headers.Add("Affinity-Actor-Type", *request.AffinityActorType)
	}
	headers.Add("Content-Type", "application/json")
	var response *affinity.CreatePatientAddressResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.CreatePatientAddressResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ArchivePatientAddress(
	ctx context.Context,
	request *affinity.ArchivePatientAddressRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.ArchivePatientAddressResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/patients/%v/addresses/%v",
		request.PracticeID,
		request.PatientID,
		request.AddressID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	if request.AffinityActorID != nil {
		headers.Add("Affinity-Actor-Id", *request.AffinityActorID)
	}
	if request.AffinityActorType != nil {
		headers.Add("Affinity-Actor-Type", *request.AffinityActorType)
	}

	var response *affinity.ArchivePatientAddressResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.ArchivePatientAddressResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdatePatientAddress(
	ctx context.Context,
	request *affinity.UpdatePatientAddressRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.UpdatePatientAddressResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/patients/%v/addresses/%v",
		request.PracticeID,
		request.PatientID,
		request.AddressID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	if request.AffinityActorID != nil {
		headers.Add("Affinity-Actor-Id", *request.AffinityActorID)
	}
	if request.AffinityActorType != nil {
		headers.Add("Affinity-Actor-Type", *request.AffinityActorType)
	}
	headers.Add("Content-Type", "application/json")
	var response *affinity.UpdatePatientAddressResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.UpdatePatientAddressResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) SetDefaultPatientAddress(
	ctx context.Context,
	request *affinity.SetDefaultPatientAddressRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.SetDefaultPatientAddressResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/patients/%v/addresses/%v/default",
		request.PracticeID,
		request.PatientID,
		request.AddressID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	if request.AffinityActorID != nil {
		headers.Add("Affinity-Actor-Id", *request.AffinityActorID)
	}
	if request.AffinityActorType != nil {
		headers.Add("Affinity-Actor-Type", *request.AffinityActorType)
	}

	var response *affinity.SetDefaultPatientAddressResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.SetDefaultPatientAddressResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListPatients(
	ctx context.Context,
	request *affinity.ListPatientsRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.ListPatientsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/patients",
		request.PracticeID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.AffinityActorID != nil {
		headers.Add("Affinity-Actor-Id", *request.AffinityActorID)
	}
	if request.AffinityActorType != nil {
		headers.Add("Affinity-Actor-Type", *request.AffinityActorType)
	}

	var response *affinity.ListPatientsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.ListPatientsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreatePatient(
	ctx context.Context,
	request *affinity.CreatePatientRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.CreatePatientResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/patients",
		request.PracticeID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	if request.AffinityActorID != nil {
		headers.Add("Affinity-Actor-Id", *request.AffinityActorID)
	}
	if request.AffinityActorType != nil {
		headers.Add("Affinity-Actor-Type", *request.AffinityActorType)
	}
	headers.Add("Content-Type", "application/json")
	var response *affinity.CreatePatientResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.CreatePatientResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetPatient(
	ctx context.Context,
	request *affinity.GetPatientRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.GetPatientResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/patients/%v",
		request.PracticeID,
		request.PatientID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.AffinityActorID != nil {
		headers.Add("Affinity-Actor-Id", *request.AffinityActorID)
	}
	if request.AffinityActorType != nil {
		headers.Add("Affinity-Actor-Type", *request.AffinityActorType)
	}

	var response *affinity.GetPatientResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.GetPatientResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeletePatient(
	ctx context.Context,
	request *affinity.DeletePatientRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.DeletePatientResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/patients/%v",
		request.PracticeID,
		request.PatientID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	if request.AffinityActorID != nil {
		headers.Add("Affinity-Actor-Id", *request.AffinityActorID)
	}
	if request.AffinityActorType != nil {
		headers.Add("Affinity-Actor-Type", *request.AffinityActorType)
	}

	var response *affinity.DeletePatientResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.DeletePatientResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdatePatient(
	ctx context.Context,
	request *affinity.UpdatePatientRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.UpdatePatientResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/patients/%v",
		request.PracticeID,
		request.PatientID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	if request.AffinityActorID != nil {
		headers.Add("Affinity-Actor-Id", *request.AffinityActorID)
	}
	if request.AffinityActorType != nil {
		headers.Add("Affinity-Actor-Type", *request.AffinityActorType)
	}
	headers.Add("Content-Type", "application/json")
	var response *affinity.UpdatePatientResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.UpdatePatientResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetPatientAllergies(
	ctx context.Context,
	request *affinity.GetPatientAllergiesRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.GetPatientAllergiesResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/patients/%v/allergies",
		request.PracticeID,
		request.PatientID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.AffinityActorID != nil {
		headers.Add("Affinity-Actor-Id", *request.AffinityActorID)
	}
	if request.AffinityActorType != nil {
		headers.Add("Affinity-Actor-Type", *request.AffinityActorType)
	}

	var response *affinity.GetPatientAllergiesResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.GetPatientAllergiesResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ReplacePatientAllergies(
	ctx context.Context,
	request *affinity.ReplacePatientAllergiesRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.ReplacePatientAllergiesResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/patients/%v/allergies",
		request.PracticeID,
		request.PatientID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	if request.AffinityActorID != nil {
		headers.Add("Affinity-Actor-Id", *request.AffinityActorID)
	}
	if request.AffinityActorType != nil {
		headers.Add("Affinity-Actor-Type", *request.AffinityActorType)
	}
	headers.Add("Content-Type", "application/json")
	var response *affinity.ReplacePatientAllergiesResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.ReplacePatientAllergiesResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
