// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"

	affinity "github.com/affinity-health/affinity-go"
	core "github.com/affinity-health/affinity-go/core"
	internal "github.com/affinity-health/affinity-go/internal"
	option "github.com/affinity-health/affinity-go/option"
	team "github.com/affinity-health/affinity-go/team"
	licenses "github.com/affinity-health/affinity-go/team/prescribers/licenses"
)

type Client struct {
	WithRawResponse *RawClient
	Licenses        *licenses.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Licenses:        licenses.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Requires team:read. Filter practice prescribers by name, NPI, state, and practice status. Records include submitted licenses and their IDs. Signing authority also requires an active account connection, Live practice access, and prescription eligibility.
func (c *Client) List(
	ctx context.Context,
	request *team.ListPrescribersRequest,
	opts ...option.RequestOption,
) (*affinity.ListPracticeTeamPrescribersResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires team:read. Returns the clinical profile and submitted licenses, including license IDs. This is setup information, not a signing authorization.
func (c *Client) Get(
	ctx context.Context,
	request *team.GetPrescribersRequest,
	opts ...option.RequestOption,
) (*affinity.GetPracticeTeamPrescriberResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires team:write. Set practiceStatus to inactive to remove prescribing access in this practice, or active to restore an existing association. This does not create membership or signing authority. Practice status applies to Test and Live. Shared identity and license edits require Affinity support.
func (c *Client) Update(
	ctx context.Context,
	request *team.UpdatePracticeTeamPrescriberRequest,
	opts ...option.RequestOption,
) (*affinity.UpdatePracticeTeamPrescriberResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
