// Code generated by Fern. DO NOT EDIT.

package client

import (
 "github.com/google/uuid"
	context "context"
	http "net/http"

	affinity "github.com/affinity-health/affinity-go"
	core "github.com/affinity-health/affinity-go/core"
	internal "github.com/affinity-health/affinity-go/internal"
	option "github.com/affinity-health/affinity-go/option"
	team "github.com/affinity-health/affinity-go/team"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) List(
	ctx context.Context,
	request *team.ListPrescribersRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.ListPracticeTeamPrescribersResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/team/prescribers",
		request.PracticeID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *affinity.ListPracticeTeamPrescribersResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(team.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.ListPracticeTeamPrescribersResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Get(
	ctx context.Context,
	request *team.GetPrescribersRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.GetPracticeTeamPrescriberResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/team/prescribers/%v",
		request.PracticeID,
		request.PrescriberID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *affinity.GetPracticeTeamPrescriberResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(team.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.GetPracticeTeamPrescriberResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Update(
	ctx context.Context,
	request *team.UpdatePracticeTeamPrescriberRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.UpdatePracticeTeamPrescriberResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/practices/%v/team/prescribers/%v",
		request.PracticeID,
		request.PrescriberID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
 headers.Add("Idempotency-Key", *request.IdempotencyKey)
 } else { headers.Add("Idempotency-Key", uuid.NewString()) } // affinity-sdk-auto-key
	headers.Add("Content-Type", "application/json")
	var response *affinity.UpdatePracticeTeamPrescriberResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(team.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.UpdatePracticeTeamPrescriberResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
