// Code generated by Fern. DO NOT EDIT.

package webhooks

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCreateWebhookEndpointRequest(t *testing.T) {
	t.Run("SetAffinityOrganizationID", func(t *testing.T) {
		obj := &CreateWebhookEndpointRequest{}
		var fernTestValueAffinityOrganizationID *string
		obj.SetAffinityOrganizationID(fernTestValueAffinityOrganizationID)
		assert.Equal(t, fernTestValueAffinityOrganizationID, obj.AffinityOrganizationID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &CreateWebhookEndpointRequest{}
		var fernTestValueIdempotencyKey string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPracticeIDs", func(t *testing.T) {
		obj := &CreateWebhookEndpointRequest{}
		var fernTestValuePracticeIDs []string
		obj.SetPracticeIDs(fernTestValuePracticeIDs)
		assert.Equal(t, fernTestValuePracticeIDs, obj.PracticeIDs)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDescription", func(t *testing.T) {
		obj := &CreateWebhookEndpointRequest{}
		var fernTestValueDescription *string
		obj.SetDescription(fernTestValueDescription)
		assert.Equal(t, fernTestValueDescription, obj.Description)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPayloadStyle", func(t *testing.T) {
		obj := &CreateWebhookEndpointRequest{}
		var fernTestValuePayloadStyle *CreateWebhookEndpointRequestPayloadStyle
		obj.SetPayloadStyle(fernTestValuePayloadStyle)
		assert.Equal(t, fernTestValuePayloadStyle, obj.PayloadStyle)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSubscribedEvents", func(t *testing.T) {
		obj := &CreateWebhookEndpointRequest{}
		var fernTestValueSubscribedEvents []CreateWebhookEndpointRequestSubscribedEventsItem
		obj.SetSubscribedEvents(fernTestValueSubscribedEvents)
		assert.Equal(t, fernTestValueSubscribedEvents, obj.SubscribedEvents)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetURL", func(t *testing.T) {
		obj := &CreateWebhookEndpointRequest{}
		var fernTestValueURL string
		obj.SetURL(fernTestValueURL)
		assert.Equal(t, fernTestValueURL, obj.URL)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateWebhookEndpointRequest(t *testing.T) {
	t.Run("SetAffinityOrganizationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateWebhookEndpointRequest{}
		var fernTestValueAffinityOrganizationID *string

		// Act
		obj.SetAffinityOrganizationID(fernTestValueAffinityOrganizationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateWebhookEndpointRequest{}
		var fernTestValueIdempotencyKey string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPracticeIDs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateWebhookEndpointRequest{}
		var fernTestValuePracticeIDs []string

		// Act
		obj.SetPracticeIDs(fernTestValuePracticeIDs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDescription_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateWebhookEndpointRequest{}
		var fernTestValueDescription *string

		// Act
		obj.SetDescription(fernTestValueDescription)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPayloadStyle_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateWebhookEndpointRequest{}
		var fernTestValuePayloadStyle *CreateWebhookEndpointRequestPayloadStyle

		// Act
		obj.SetPayloadStyle(fernTestValuePayloadStyle)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSubscribedEvents_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateWebhookEndpointRequest{}
		var fernTestValueSubscribedEvents []CreateWebhookEndpointRequestSubscribedEventsItem

		// Act
		obj.SetSubscribedEvents(fernTestValueSubscribedEvents)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateWebhookEndpointRequest{}
		var fernTestValueURL string

		// Act
		obj.SetURL(fernTestValueURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDeleteEndpointsRequest(t *testing.T) {
	t.Run("SetAffinityOrganizationID", func(t *testing.T) {
		obj := &DeleteEndpointsRequest{}
		var fernTestValueAffinityOrganizationID *string
		obj.SetAffinityOrganizationID(fernTestValueAffinityOrganizationID)
		assert.Equal(t, fernTestValueAffinityOrganizationID, obj.AffinityOrganizationID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &DeleteEndpointsRequest{}
		var fernTestValueIdempotencyKey string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndpointID", func(t *testing.T) {
		obj := &DeleteEndpointsRequest{}
		var fernTestValueEndpointID string
		obj.SetEndpointID(fernTestValueEndpointID)
		assert.Equal(t, fernTestValueEndpointID, obj.EndpointID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDeleteEndpointsRequest(t *testing.T) {
	t.Run("SetAffinityOrganizationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteEndpointsRequest{}
		var fernTestValueAffinityOrganizationID *string

		// Act
		obj.SetAffinityOrganizationID(fernTestValueAffinityOrganizationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteEndpointsRequest{}
		var fernTestValueIdempotencyKey string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndpointID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteEndpointsRequest{}
		var fernTestValueEndpointID string

		// Act
		obj.SetEndpointID(fernTestValueEndpointID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListEndpointsRequest(t *testing.T) {
	t.Run("SetAffinityOrganizationID", func(t *testing.T) {
		obj := &ListEndpointsRequest{}
		var fernTestValueAffinityOrganizationID *string
		obj.SetAffinityOrganizationID(fernTestValueAffinityOrganizationID)
		assert.Equal(t, fernTestValueAffinityOrganizationID, obj.AffinityOrganizationID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndingBefore", func(t *testing.T) {
		obj := &ListEndpointsRequest{}
		var fernTestValueEndingBefore *string
		obj.SetEndingBefore(fernTestValueEndingBefore)
		assert.Equal(t, fernTestValueEndingBefore, obj.EndingBefore)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLimit", func(t *testing.T) {
		obj := &ListEndpointsRequest{}
		var fernTestValueLimit *int
		obj.SetLimit(fernTestValueLimit)
		assert.Equal(t, fernTestValueLimit, obj.Limit)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStartingAfter", func(t *testing.T) {
		obj := &ListEndpointsRequest{}
		var fernTestValueStartingAfter *string
		obj.SetStartingAfter(fernTestValueStartingAfter)
		assert.Equal(t, fernTestValueStartingAfter, obj.StartingAfter)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListEndpointsRequest(t *testing.T) {
	t.Run("SetAffinityOrganizationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEndpointsRequest{}
		var fernTestValueAffinityOrganizationID *string

		// Act
		obj.SetAffinityOrganizationID(fernTestValueAffinityOrganizationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndingBefore_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEndpointsRequest{}
		var fernTestValueEndingBefore *string

		// Act
		obj.SetEndingBefore(fernTestValueEndingBefore)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEndpointsRequest{}
		var fernTestValueLimit *int

		// Act
		obj.SetLimit(fernTestValueLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStartingAfter_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEndpointsRequest{}
		var fernTestValueStartingAfter *string

		// Act
		obj.SetStartingAfter(fernTestValueStartingAfter)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRotateSecretEndpointsRequest(t *testing.T) {
	t.Run("SetAffinityOrganizationID", func(t *testing.T) {
		obj := &RotateSecretEndpointsRequest{}
		var fernTestValueAffinityOrganizationID *string
		obj.SetAffinityOrganizationID(fernTestValueAffinityOrganizationID)
		assert.Equal(t, fernTestValueAffinityOrganizationID, obj.AffinityOrganizationID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &RotateSecretEndpointsRequest{}
		var fernTestValueIdempotencyKey string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndpointID", func(t *testing.T) {
		obj := &RotateSecretEndpointsRequest{}
		var fernTestValueEndpointID string
		obj.SetEndpointID(fernTestValueEndpointID)
		assert.Equal(t, fernTestValueEndpointID, obj.EndpointID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitRotateSecretEndpointsRequest(t *testing.T) {
	t.Run("SetAffinityOrganizationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RotateSecretEndpointsRequest{}
		var fernTestValueAffinityOrganizationID *string

		// Act
		obj.SetAffinityOrganizationID(fernTestValueAffinityOrganizationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RotateSecretEndpointsRequest{}
		var fernTestValueIdempotencyKey string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndpointID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RotateSecretEndpointsRequest{}
		var fernTestValueEndpointID string

		// Act
		obj.SetEndpointID(fernTestValueEndpointID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTestEndpointsRequest(t *testing.T) {
	t.Run("SetAffinityOrganizationID", func(t *testing.T) {
		obj := &TestEndpointsRequest{}
		var fernTestValueAffinityOrganizationID *string
		obj.SetAffinityOrganizationID(fernTestValueAffinityOrganizationID)
		assert.Equal(t, fernTestValueAffinityOrganizationID, obj.AffinityOrganizationID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &TestEndpointsRequest{}
		var fernTestValueIdempotencyKey string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndpointID", func(t *testing.T) {
		obj := &TestEndpointsRequest{}
		var fernTestValueEndpointID string
		obj.SetEndpointID(fernTestValueEndpointID)
		assert.Equal(t, fernTestValueEndpointID, obj.EndpointID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitTestEndpointsRequest(t *testing.T) {
	t.Run("SetAffinityOrganizationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TestEndpointsRequest{}
		var fernTestValueAffinityOrganizationID *string

		// Act
		obj.SetAffinityOrganizationID(fernTestValueAffinityOrganizationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TestEndpointsRequest{}
		var fernTestValueIdempotencyKey string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndpointID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TestEndpointsRequest{}
		var fernTestValueEndpointID string

		// Act
		obj.SetEndpointID(fernTestValueEndpointID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpdateWebhookEndpointRequest(t *testing.T) {
	t.Run("SetAffinityOrganizationID", func(t *testing.T) {
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValueAffinityOrganizationID *string
		obj.SetAffinityOrganizationID(fernTestValueAffinityOrganizationID)
		assert.Equal(t, fernTestValueAffinityOrganizationID, obj.AffinityOrganizationID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValueIdempotencyKey string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndpointID", func(t *testing.T) {
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValueEndpointID string
		obj.SetEndpointID(fernTestValueEndpointID)
		assert.Equal(t, fernTestValueEndpointID, obj.EndpointID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPracticeIDs", func(t *testing.T) {
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValuePracticeIDs []string
		obj.SetPracticeIDs(fernTestValuePracticeIDs)
		assert.Equal(t, fernTestValuePracticeIDs, obj.PracticeIDs)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDescription", func(t *testing.T) {
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValueDescription *string
		obj.SetDescription(fernTestValueDescription)
		assert.Equal(t, fernTestValueDescription, obj.Description)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPayloadStyle", func(t *testing.T) {
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValuePayloadStyle *UpdateWebhookEndpointRequestPayloadStyle
		obj.SetPayloadStyle(fernTestValuePayloadStyle)
		assert.Equal(t, fernTestValuePayloadStyle, obj.PayloadStyle)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValueStatus *UpdateWebhookEndpointRequestStatus
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSubscribedEvents", func(t *testing.T) {
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValueSubscribedEvents []UpdateWebhookEndpointRequestSubscribedEventsItem
		obj.SetSubscribedEvents(fernTestValueSubscribedEvents)
		assert.Equal(t, fernTestValueSubscribedEvents, obj.SubscribedEvents)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetURL", func(t *testing.T) {
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValueURL *string
		obj.SetURL(fernTestValueURL)
		assert.Equal(t, fernTestValueURL, obj.URL)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitUpdateWebhookEndpointRequest(t *testing.T) {
	t.Run("SetAffinityOrganizationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValueAffinityOrganizationID *string

		// Act
		obj.SetAffinityOrganizationID(fernTestValueAffinityOrganizationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValueIdempotencyKey string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndpointID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValueEndpointID string

		// Act
		obj.SetEndpointID(fernTestValueEndpointID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPracticeIDs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValuePracticeIDs []string

		// Act
		obj.SetPracticeIDs(fernTestValuePracticeIDs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDescription_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValueDescription *string

		// Act
		obj.SetDescription(fernTestValueDescription)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPayloadStyle_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValuePayloadStyle *UpdateWebhookEndpointRequestPayloadStyle

		// Act
		obj.SetPayloadStyle(fernTestValuePayloadStyle)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValueStatus *UpdateWebhookEndpointRequestStatus

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSubscribedEvents_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValueSubscribedEvents []UpdateWebhookEndpointRequestSubscribedEventsItem

		// Act
		obj.SetSubscribedEvents(fernTestValueSubscribedEvents)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateWebhookEndpointRequest{}
		var fernTestValueURL *string

		// Act
		obj.SetURL(fernTestValueURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestEnumCreateWebhookEndpointRequestPayloadStyle(t *testing.T) {
	t.Run("NewFromString_thin", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestPayloadStyleFromString("thin")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestPayloadStyle("thin"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_snapshot", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestPayloadStyleFromString("snapshot")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestPayloadStyle("snapshot"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewCreateWebhookEndpointRequestPayloadStyleFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewCreateWebhookEndpointRequestPayloadStyleFromString("thin")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumCreateWebhookEndpointRequestSubscribedEventsItem(t *testing.T) {
	t.Run("NewFromString_webhook_endpoint_test", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("webhook_endpoint.test")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("webhook_endpoint.test"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cancellation_requested", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("cancellation.requested")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("cancellation.requested"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cancellation_sent", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("cancellation.sent")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("cancellation.sent"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cancellation_confirmed", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("cancellation.confirmed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("cancellation.confirmed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cancellation_rejected", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("cancellation.rejected")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("cancellation.rejected"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cancellation_failed", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("cancellation.failed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("cancellation.failed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cancellation_too_late", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("cancellation.too_late")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("cancellation.too_late"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_created", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("order.created")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("order.created"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_updated", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("order.updated")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("order.updated"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_review_requested", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("order.review_requested")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("order.review_requested"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_changes_requested", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("order.changes_requested")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("order.changes_requested"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_signed", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("order.signed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("order.signed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_rejected", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("order.rejected")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("order.rejected"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_submitted", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("order.submitted")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("order.submitted"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_accepted", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("order.accepted")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("order.accepted"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_processing", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("order.processing")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("order.processing"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_shipped", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("order.shipped")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("order.shipped"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_delivered", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("order.delivered")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("order.delivered"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_blocked", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("order.blocked")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("order.blocked"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_cancelled", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("order.cancelled")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateWebhookEndpointRequestSubscribedEventsItem("order.cancelled"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewCreateWebhookEndpointRequestSubscribedEventsItemFromString("webhook_endpoint.test")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumUpdateWebhookEndpointRequestPayloadStyle(t *testing.T) {
	t.Run("NewFromString_thin", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestPayloadStyleFromString("thin")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestPayloadStyle("thin"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_snapshot", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestPayloadStyleFromString("snapshot")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestPayloadStyle("snapshot"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewUpdateWebhookEndpointRequestPayloadStyleFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewUpdateWebhookEndpointRequestPayloadStyleFromString("thin")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumUpdateWebhookEndpointRequestStatus(t *testing.T) {
	t.Run("NewFromString_active", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestStatusFromString("active")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestStatus("active"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_suspended", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestStatusFromString("suspended")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestStatus("suspended"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_disabled", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestStatusFromString("disabled")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestStatus("disabled"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewUpdateWebhookEndpointRequestStatusFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewUpdateWebhookEndpointRequestStatusFromString("active")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumUpdateWebhookEndpointRequestSubscribedEventsItem(t *testing.T) {
	t.Run("NewFromString_webhook_endpoint_test", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("webhook_endpoint.test")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("webhook_endpoint.test"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cancellation_requested", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("cancellation.requested")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("cancellation.requested"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cancellation_sent", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("cancellation.sent")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("cancellation.sent"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cancellation_confirmed", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("cancellation.confirmed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("cancellation.confirmed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cancellation_rejected", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("cancellation.rejected")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("cancellation.rejected"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cancellation_failed", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("cancellation.failed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("cancellation.failed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cancellation_too_late", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("cancellation.too_late")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("cancellation.too_late"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_created", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("order.created")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("order.created"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_updated", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("order.updated")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("order.updated"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_review_requested", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("order.review_requested")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("order.review_requested"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_changes_requested", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("order.changes_requested")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("order.changes_requested"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_signed", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("order.signed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("order.signed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_rejected", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("order.rejected")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("order.rejected"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_submitted", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("order.submitted")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("order.submitted"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_accepted", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("order.accepted")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("order.accepted"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_processing", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("order.processing")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("order.processing"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_shipped", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("order.shipped")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("order.shipped"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_delivered", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("order.delivered")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("order.delivered"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_blocked", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("order.blocked")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("order.blocked"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_order_cancelled", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("order.cancelled")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateWebhookEndpointRequestSubscribedEventsItem("order.cancelled"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewUpdateWebhookEndpointRequestSubscribedEventsItemFromString("webhook_endpoint.test")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}
