// Code generated by Fern. DO NOT EDIT.

package webhooks

import (
	fmt "fmt"
	big "math/big"
)

var (
	getEventsRequestFieldAffinityOrganizationID = big.NewInt(1 << 0)
	getEventsRequestFieldEventID                = big.NewInt(1 << 1)
)

type GetEventsRequest struct {
	// Defaults to the API key organization. A platform may select a practice or pharmacy only with an explicit webhook grant in this mode. This changes the webhook owner, not the caller or event subscriptions.
	AffinityOrganizationID *string `json:"-" url:"-"`
	EventID                string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetEventsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAffinityOrganizationID sets the AffinityOrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEventsRequest) SetAffinityOrganizationID(affinityOrganizationID *string) {
	g.AffinityOrganizationID = affinityOrganizationID
	g.require(getEventsRequestFieldAffinityOrganizationID)
}

// SetEventID sets the EventID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEventsRequest) SetEventID(eventID string) {
	g.EventID = eventID
	g.require(getEventsRequestFieldEventID)
}

var (
	listEventsRequestFieldAffinityOrganizationID = big.NewInt(1 << 0)
	listEventsRequestFieldEndingBefore           = big.NewInt(1 << 1)
	listEventsRequestFieldLimit                  = big.NewInt(1 << 2)
	listEventsRequestFieldStatus                 = big.NewInt(1 << 3)
	listEventsRequestFieldStartingAfter          = big.NewInt(1 << 4)
)

type ListEventsRequest struct {
	// Defaults to the API key organization. A platform may select a practice or pharmacy only with an explicit webhook grant in this mode. This changes the webhook owner, not the caller or event subscriptions.
	AffinityOrganizationID *string                  `json:"-" url:"-"`
	EndingBefore           *string                  `json:"-" url:"endingBefore,omitempty"`
	Limit                  *int                     `json:"-" url:"limit,omitempty"`
	Status                 *ListEventsRequestStatus `json:"-" url:"status,omitempty"`
	StartingAfter          *string                  `json:"-" url:"startingAfter,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListEventsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAffinityOrganizationID sets the AffinityOrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEventsRequest) SetAffinityOrganizationID(affinityOrganizationID *string) {
	l.AffinityOrganizationID = affinityOrganizationID
	l.require(listEventsRequestFieldAffinityOrganizationID)
}

// SetEndingBefore sets the EndingBefore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEventsRequest) SetEndingBefore(endingBefore *string) {
	l.EndingBefore = endingBefore
	l.require(listEventsRequestFieldEndingBefore)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEventsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listEventsRequestFieldLimit)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEventsRequest) SetStatus(status *ListEventsRequestStatus) {
	l.Status = status
	l.require(listEventsRequestFieldStatus)
}

// SetStartingAfter sets the StartingAfter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEventsRequest) SetStartingAfter(startingAfter *string) {
	l.StartingAfter = startingAfter
	l.require(listEventsRequestFieldStartingAfter)
}

var (
	replayEventsRequestFieldAffinityOrganizationID = big.NewInt(1 << 0)
	replayEventsRequestFieldIdempotencyKey         = big.NewInt(1 << 1)
	replayEventsRequestFieldEventID                = big.NewInt(1 << 2)
)

type ReplayEventsRequest struct {
	// Defaults to the API key organization. A platform may select a practice or pharmacy only with an explicit webhook grant in this mode. This changes the webhook owner, not the caller or event subscriptions.
	AffinityOrganizationID *string `json:"-" url:"-"`
	IdempotencyKey         string  `json:"-" url:"-"`
	EventID                string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReplayEventsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetAffinityOrganizationID sets the AffinityOrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplayEventsRequest) SetAffinityOrganizationID(affinityOrganizationID *string) {
	r.AffinityOrganizationID = affinityOrganizationID
	r.require(replayEventsRequestFieldAffinityOrganizationID)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplayEventsRequest) SetIdempotencyKey(idempotencyKey string) {
	r.IdempotencyKey = idempotencyKey
	r.require(replayEventsRequestFieldIdempotencyKey)
}

// SetEventID sets the EventID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplayEventsRequest) SetEventID(eventID string) {
	r.EventID = eventID
	r.require(replayEventsRequestFieldEventID)
}

type ListEventsRequestStatus string

const (
	ListEventsRequestStatusAll       ListEventsRequestStatus = "all"
	ListEventsRequestStatusDelivered ListEventsRequestStatus = "delivered"
	ListEventsRequestStatusFailed    ListEventsRequestStatus = "failed"
	ListEventsRequestStatusPending   ListEventsRequestStatus = "pending"
)

func NewListEventsRequestStatusFromString(s string) (ListEventsRequestStatus, error) {
	switch s {
	case "all":
		return ListEventsRequestStatusAll, nil
	case "delivered":
		return ListEventsRequestStatusDelivered, nil
	case "failed":
		return ListEventsRequestStatusFailed, nil
	case "pending":
		return ListEventsRequestStatusPending, nil
	}
	var t ListEventsRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListEventsRequestStatus) Ptr() *ListEventsRequestStatus {
	return &l
}
