// Code generated by Fern. DO NOT EDIT.

package webhooks

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/affinity-health/affinity-go/internal"
	big "math/big"
)

var (
	listGrantsRequestFieldLimit         = big.NewInt(1 << 0)
	listGrantsRequestFieldStartingAfter = big.NewInt(1 << 1)
	listGrantsRequestFieldEndingBefore  = big.NewInt(1 << 2)
)

type ListGrantsRequest struct {
	Limit         *int    `json:"-" url:"limit,omitempty"`
	StartingAfter *string `json:"-" url:"startingAfter,omitempty"`
	EndingBefore  *string `json:"-" url:"endingBefore,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListGrantsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGrantsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listGrantsRequestFieldLimit)
}

// SetStartingAfter sets the StartingAfter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGrantsRequest) SetStartingAfter(startingAfter *string) {
	l.StartingAfter = startingAfter
	l.require(listGrantsRequestFieldStartingAfter)
}

// SetEndingBefore sets the EndingBefore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGrantsRequest) SetEndingBefore(endingBefore *string) {
	l.EndingBefore = endingBefore
	l.require(listGrantsRequestFieldEndingBefore)
}

var (
	revokeGrantsRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	revokeGrantsRequestFieldPlatformID     = big.NewInt(1 << 1)
)

type RevokeGrantsRequest struct {
	IdempotencyKey string `json:"-" url:"-"`
	PlatformID     string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RevokeGrantsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeGrantsRequest) SetIdempotencyKey(idempotencyKey string) {
	r.IdempotencyKey = idempotencyKey
	r.require(revokeGrantsRequestFieldIdempotencyKey)
}

// SetPlatformID sets the PlatformID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeGrantsRequest) SetPlatformID(platformID string) {
	r.PlatformID = platformID
	r.require(revokeGrantsRequestFieldPlatformID)
}

var (
	saveWebhookGrantRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	saveWebhookGrantRequestFieldPlatformID     = big.NewInt(1 << 1)
	saveWebhookGrantRequestFieldScopes         = big.NewInt(1 << 2)
)

type SaveWebhookGrantRequest struct {
	IdempotencyKey string                              `json:"-" url:"-"`
	PlatformID     string                              `json:"-" url:"-"`
	Scopes         []SaveWebhookGrantRequestScopesItem `json:"scopes" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SaveWebhookGrantRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SaveWebhookGrantRequest) SetIdempotencyKey(idempotencyKey string) {
	s.IdempotencyKey = idempotencyKey
	s.require(saveWebhookGrantRequestFieldIdempotencyKey)
}

// SetPlatformID sets the PlatformID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SaveWebhookGrantRequest) SetPlatformID(platformID string) {
	s.PlatformID = platformID
	s.require(saveWebhookGrantRequestFieldPlatformID)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SaveWebhookGrantRequest) SetScopes(scopes []SaveWebhookGrantRequestScopesItem) {
	s.Scopes = scopes
	s.require(saveWebhookGrantRequestFieldScopes)
}

func (s *SaveWebhookGrantRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SaveWebhookGrantRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SaveWebhookGrantRequest(body)
	return nil
}

func (s *SaveWebhookGrantRequest) MarshalJSON() ([]byte, error) {
	type embed SaveWebhookGrantRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

type SaveWebhookGrantRequestScopesItem string

const (
	SaveWebhookGrantRequestScopesItemWebhooksRead  SaveWebhookGrantRequestScopesItem = "webhooks:read"
	SaveWebhookGrantRequestScopesItemWebhooksWrite SaveWebhookGrantRequestScopesItem = "webhooks:write"
)

func NewSaveWebhookGrantRequestScopesItemFromString(s string) (SaveWebhookGrantRequestScopesItem, error) {
	switch s {
	case "webhooks:read":
		return SaveWebhookGrantRequestScopesItemWebhooksRead, nil
	case "webhooks:write":
		return SaveWebhookGrantRequestScopesItemWebhooksWrite, nil
	}
	var t SaveWebhookGrantRequestScopesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SaveWebhookGrantRequestScopesItem) Ptr() *SaveWebhookGrantRequestScopesItem {
	return &s
}
