// Code generated by Fern. DO NOT EDIT.

package webhooks

import (
	context "context"
	http "net/http"

	affinity "github.com/affinity-health/affinity-go"
	core "github.com/affinity-health/affinity-go/core"
	internal "github.com/affinity-health/affinity-go/internal"
	option "github.com/affinity-health/affinity-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListWebhookEndpoints(
	ctx context.Context,
	request *affinity.ListWebhookEndpointsRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.ListWebhookEndpointsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := baseURL + "/v1/webhook-endpoints"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.AffinityOrganizationID != nil {
		headers.Add("X-Affinity-Organization-Id", *request.AffinityOrganizationID)
	}

	var response *affinity.ListWebhookEndpointsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.ListWebhookEndpointsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateWebhookEndpoint(
	ctx context.Context,
	request *affinity.CreateWebhookEndpointRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.CreateWebhookEndpointResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := baseURL + "/v1/webhook-endpoints"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.AffinityOrganizationID != nil {
		headers.Add("X-Affinity-Organization-Id", *request.AffinityOrganizationID)
	}
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	headers.Add("Content-Type", "application/json")
	var response *affinity.CreateWebhookEndpointResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.CreateWebhookEndpointResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteWebhookEndpoint(
	ctx context.Context,
	request *affinity.DeleteWebhookEndpointRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.DeleteWebhookEndpointResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/webhook-endpoints/%v",
		request.EndpointID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.AffinityOrganizationID != nil {
		headers.Add("X-Affinity-Organization-Id", *request.AffinityOrganizationID)
	}
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	var response *affinity.DeleteWebhookEndpointResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.DeleteWebhookEndpointResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdateWebhookEndpoint(
	ctx context.Context,
	request *affinity.UpdateWebhookEndpointRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.UpdateWebhookEndpointResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/webhook-endpoints/%v",
		request.EndpointID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.AffinityOrganizationID != nil {
		headers.Add("X-Affinity-Organization-Id", *request.AffinityOrganizationID)
	}
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	headers.Add("Content-Type", "application/json")
	var response *affinity.UpdateWebhookEndpointResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.UpdateWebhookEndpointResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) RotateWebhookEndpointSecret(
	ctx context.Context,
	request *affinity.RotateWebhookEndpointSecretRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.RotateWebhookEndpointSecretResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/webhook-endpoints/%v/rotate-secret",
		request.EndpointID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.AffinityOrganizationID != nil {
		headers.Add("X-Affinity-Organization-Id", *request.AffinityOrganizationID)
	}
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	var response *affinity.RotateWebhookEndpointSecretResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.RotateWebhookEndpointSecretResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) TestWebhookEndpoint(
	ctx context.Context,
	request *affinity.TestWebhookEndpointRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.TestWebhookEndpointResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/webhook-endpoints/%v/test",
		request.EndpointID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.AffinityOrganizationID != nil {
		headers.Add("X-Affinity-Organization-Id", *request.AffinityOrganizationID)
	}
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	var response *affinity.TestWebhookEndpointResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.TestWebhookEndpointResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListWebhookEvents(
	ctx context.Context,
	request *affinity.ListWebhookEventsRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.ListWebhookEventsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := baseURL + "/v1/webhook-events"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.AffinityOrganizationID != nil {
		headers.Add("X-Affinity-Organization-Id", *request.AffinityOrganizationID)
	}

	var response *affinity.ListWebhookEventsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.ListWebhookEventsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetWebhookEvent(
	ctx context.Context,
	request *affinity.GetWebhookEventRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.GetWebhookEventResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/webhook-events/%v",
		request.EventID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.AffinityOrganizationID != nil {
		headers.Add("X-Affinity-Organization-Id", *request.AffinityOrganizationID)
	}

	var response *affinity.GetWebhookEventResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.GetWebhookEventResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ReplayWebhookEvent(
	ctx context.Context,
	request *affinity.ReplayWebhookEventRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.ReplayWebhookEventResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/webhook-events/%v/replay",
		request.EventID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.AffinityOrganizationID != nil {
		headers.Add("X-Affinity-Organization-Id", *request.AffinityOrganizationID)
	}
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	var response *affinity.ReplayWebhookEventResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.ReplayWebhookEventResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListWebhookGrants(
	ctx context.Context,
	request *affinity.ListWebhookGrantsRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.ListWebhookGrantsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := baseURL + "/v1/webhook-grants"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *affinity.ListWebhookGrantsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.ListWebhookGrantsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) SaveWebhookGrant(
	ctx context.Context,
	request *affinity.SaveWebhookGrantRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.SaveWebhookGrantResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/webhook-grants/%v",
		request.PlatformID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	headers.Add("Content-Type", "application/json")
	var response *affinity.SaveWebhookGrantResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.SaveWebhookGrantResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) RevokeWebhookGrant(
	ctx context.Context,
	request *affinity.RevokeWebhookGrantRequest,
	opts ...option.RequestOption,
) (*core.Response[*affinity.RevokeWebhookGrantResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.joinaffinityai.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/webhook-grants/%v",
		request.PlatformID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	var response *affinity.RevokeWebhookGrantResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(affinity.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*affinity.RevokeWebhookGrantResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
